# Framing Annotation — Step 2: Improve Coverage of Draft Annotation Instructions

- **Step 2.1** — Test draft annotation instructions on a small random sample and inspect results  
- **Step 2.2** — Run multiple annotation runs (briseus equivalent) to identify hard cases where the model disagrees with itself

The goal at this stage is **not** to achieve high reliability yet — it is to make sure your annotation instructions cover all cases you encounter in the data. Hard cases and mislabeled cases will tell you where to add decision rules and clarify your codebook.

## Setup

Load libraries and configure the API connection. The API key is loaded from a `.env` file — make sure you have a `.env` file in your project root with:

```
CAC_API_KEY=your_key_here
```

In [22]:
import pandas as pd
import requests
import os
import time
from dotenv import load_dotenv
from pathlib import Path 
from collections import Counter

load_dotenv()
api_key = os.getenv("CAC_API_KEY")

HOST  = "https://maki.uni-mannheim.de/v1"
MODEL = "ministral-3-14b"

print(f"API key loaded: {'YES' if api_key else 'NO — check your .env file'}")
print(f"Host: {HOST}")
print(f"Model: {MODEL}")

API key loaded: YES
Host: https://maki.uni-mannheim.de/v1
Model: ministral-3-14b

In [2]:
!echo $CAC_API_KEY

sk-T4QZ6ao-ia3njvfff13KEQ

## Step 1 Draft: Annotation Instructions

These are the **Step 1 annotation instructions** written based on the theoretical framework from Freudenthaler et al. (under review). The **Immigration and Crime Frame** (Security Threat Frame in the paper) belongs to dimension 5 of the framework — the ideological layer that links structural inequalities to attitudes and behaviors.

According to the paper, security threat frames portray racialized groups as implicitly or explicitly causing crime, justifying harsher policing and restrictive immigration policies.
elated to group 1 !! 
> **Note:** These instructions are a first draft and will be refined iteratively through Steps 2.1 and 2.2. Modify the `instructions` and `reminder` variables below after each round of inspection.

## NEW INSTRUCTION!

In [42]:
instructions = """Sie sind ein Experte für Inhaltsanalyse in einer Studie zur medialen Darstellung ethnischer und sozialer Gruppen in deutschen Nachrichten. Ihre Aufgabe ist es, zu klassifizieren, ob ein gegebener Nachrichtenabsatz einen Einwanderungs- und Kriminalitätsrahmen enthält und, falls ja, ob dieser negativ (Bedrohung) oder positiv (Sicherheitsgewinn/Prävention) dargestellt wird.

Sie erhalten Mehrfachabsätze aus deutschen Zeitungsartikeln. Gruppen können als [Gruppe 1] oder [andere Gruppe] bezeichnet werden. Konzentrieren Sie sich ausschließlich auf das, was explizit im Text steht. Schließen Sie keine Gruppenassoziationen, die nicht direkt ausgedrückt werden.

WICHTIG:
Ein Kriminalitäts- oder Sicherheitsrahmen liegt nur dann vor, wenn die Gruppe explizit mit Kriminalität, Sicherheit, Gefahr oder Prävention verknüpft wird.

NO_CRIME_FRAME:
Ein Absatz erhält dieses Label, wenn kein expliziter Kriminalitäts- oder Sicherheitsrahmen vorliegt. Dies gilt insbesondere wenn:
- Die Gruppe gar nicht erwähnt wird
- Kriminalität erwähnt wird, aber nicht mit der Gruppe verknüpft ist
- Die Gruppe als Opfer von Straftaten dargestellt wird
- Kriminalität auf soziale Bedingungen (Armut, Ausgrenzung etc.) zurückgeführt wird
- Der Text Kriminalitätszuschreibungen relativiert oder widerspricht („kein Generalverdacht“, „nicht alle“)
- Krieg, geopolitische Konflikte oder militärische Ereignisse beschrieben werden, ohne explizite Verknüpfung der Gruppe mit Terrorismus, Anschlägen, Gewalt gegen Zivilisten, Straftaten oder Sicherheitsbedrohungen
- Humanitäre Krisen oder Naturkatastrophen beschrieben werden
- Ein Täter erwähnt wird, aber NICHT Mitglied der Gruppe ist

CRIME_FRAME_NEG:
Ein Absatz erhält dieses Label, wenn die Gruppe als Quelle von Kriminalität oder Sicherheitsbedrohung dargestellt wird. Dies umfasst:
- Gruppe wird als Täter, Verdächtiger oder kriminell dargestellt
- Gruppe wird mit konkreten Straftaten verbunden (z.B. Diebstahl, Gewalt, Mord)
- Gruppe wird als Ursache steigender Kriminalität dargestellt
- Gruppe wird als Gefahr für öffentliche oder nationale Sicherheit dargestellt
- Migration oder Gruppenzugehörigkeit wird mit Kriminalität verknüpft
- Terrorismus oder Extremismus wird mit der Gruppe verbunden
- Physische Gewalt oder Bedrohung geht explizit von Gruppenmitgliedern aus
- Gruppe begrüßt, legitimiert, feiert, rechtfertigt oder unterstützt einen Anschlag, Terrorakt, Gewaltakt oder eine Straftat
- Gruppe stellt einen Anschlag, Terrorakt, Gewaltakt oder eine Straftat als Widerstand, heroische Operation oder legitime Handlung dar
- Gruppe erscheint als Unterstützer, Kommentator, ideologischer Bezugspunkt oder politischer Akteur, der explizit mit Zustimmung, Rechtfertigung, Feier, Unterstützung oder ideologischer Nähe zu Terrorismus, politischer Gewalt oder Straftaten verbunden wird

WICHTIG:
Die Gruppe muss klar mit der Straftat, Bedrohung, Gewaltlegitimation oder Sicherheitsgefahr verknüpft sein. Reine Erwähnung von Kriminalität reicht nicht. Eine direkte Verantwortung oder Täterschaft der Gruppe ist nicht zwingend erforderlich, wenn die Gruppe den Gewaltakt ausdrücklich legitimiert, begrüßt, feiert oder unterstützt.

CRIME_FRAME_POS:
Ein Absatz erhält dieses Label, wenn ein Sicherheits- oder Kriminalitätsrahmen vorhanden ist, aber positiv dargestellt wird. Dies umfasst:
- Maßnahmen zur Kriminalitätsbekämpfung im Zusammenhang mit der Gruppe
- Prävention (z.B. soziale Arbeit, Integration, Deradikalisierung)
- Differenzierung („kein Generalverdacht“, „nicht alle“)
- Kriminalität wird durch soziale Faktoren erklärt statt durch die Gruppe selbst
- Gruppenmitglieder wirken aktiv an Sicherheit oder Prävention mit (z.B. Polizei, Sozialarbeit)
- Maßnahmen werden als Verbesserung von Sicherheit oder Ordnung dargestellt

Entscheidungsregeln:
- Prüfen Sie zuerst, ob überhaupt ein Kriminalitäts- oder Sicherheitsrahmen vorliegt
- Wenn nein → NO_CRIME_FRAME
- Wenn ja → prüfen, ob die Darstellung negativ (Bedrohung) oder positiv (Schutz/Prävention) ist
- Wenn Gruppe als Täter, Gefahr, Unterstützer von Gewalt oder Legitimierer von Terrorismus erscheint → CRIME_FRAME_NEG
- Wenn Krieg, geopolitische Konflikte oder militärische Ereignisse vorkommen, vergeben Sie nur dann CRIME_FRAME_NEG, wenn die Gruppe explizit mit Terrorismus, Anschlägen, Gewalt gegen Zivilisten, Straftaten oder Sicherheitsbedrohungen verbunden wird
- Wenn Sicherheit, Prävention oder Differenzierung im Vordergrund steht → CRIME_FRAME_POS
- Wenn unklar oder widersprüchlich → UNCLEAR

Im Zweifelsfall:
Fragen Sie sich, ob ein Leser die Gruppe als kriminell, sicherheitsgefährdend, gewaltunterstützend oder als Sicherheitsfaktor wahrnehmen würde. Wenn nein → NO_CRIME_FRAME."""

reminder = "Vergeben Sie genau ein Label: NO_CRIME_FRAME, CRIME_FRAME_NEG oder CRIME_FRAME_POS. Achten Sie besonders darauf, dass die Gruppe explizit mit Kriminalität, Sicherheit, Terrorismus, Gewaltlegitimation oder Prävention verknüpft ist. Wenn Kriminalität erwähnt wird, aber nicht mit der Gruppe verbunden ist oder die Gruppe Opfer ist, vergeben Sie NO_CRIME_FRAME."

print("Instructions and reminder loaded.")

Instructions and reminder loaded.

Test another Instruction

## Core Functions

Three functions power the annotation pipeline:

- `annotate()` — sends a single paragraph to the API and returns the raw model output
- `parse_label()` — extracts the label from the raw output, handling misspellings and drift
- `parse_explanation()` — extracts the explanation sentence from the raw output

**On label drift:** Small LLMs sometimes output unexpected labels (e.g. `CRIME` instead of `CRIME_FRAME`, or a misspelling). The `parse_label()` function handles this by doing a fuzzy match rather than an exact match. If more than 5% of your outputs are `UNCLEAR`, revisit the reminder and output format instructions.

In [43]:
def annotate(text, instructions, reminder, temperature=0.0):
    """Send a paragraph to the API for annotation."""
    prompt = f"{instructions}\n\nNow annotate this paragraph:\n\n{text}\n\n{reminder}\n\nRespond in this format exactly:\nLabel: <NO_CRIME_FRAME or CRIME_FRAME_NEG or CRIME_FRAME_POS>\nExplanation: <one sentence explaining your choice>"

    payload = {
        "model": MODEL,
        "temperature": temperature,
        "messages": [
            {"role": "system", "content": "Sie sind ein Experte für Inhaltsanalyse. Befolgen Sie die Annotationsanweisungen genau und antworten Sie immer im angegebenen Format."},
            {"role": "user", "content": prompt}
        ]
    }
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }

    for attempt in range(3):
        try:
            response = requests.post(
                f"{HOST}/chat/completions",
                json=payload,
                headers=headers,
                timeout=120
            )
            if response.status_code == 200:
                return response.json()['choices'][0]['message']['content'].strip()
            else:
                print(f"  [attempt {attempt+1}] Status {response.status_code}")
        except Exception as e:
            print(f"  [attempt {attempt+1}] Error: {e}")
            time.sleep(5)
    return "ERROR"


def parse_label(raw_output):
    """Extract and normalize label from raw model output.
    Handles misspellings and label drift from small LLMs.
    """
    raw_upper = raw_output.upper()

    # Check NO_CRIME_FRAME first because it contains CRIME_FRAME
    if "NO_CRIME_FRAME" in raw_upper or "NO CRIME FRAME" in raw_upper:
        return "NO_CRIME_FRAME"
    elif "CRIME_FRAME_NEG" in raw_upper or "CRIME FRAME NEG" in raw_upper:
        return "CRIME_FRAME_NEG"
    elif "CRIME_FRAME_POS" in raw_upper or "CRIME FRAME POS" in raw_upper:
        return "CRIME_FRAME_POS"
    else:
        return "UNCLEAR"


def parse_explanation(raw_output):
    """Extract explanation sentence from raw model output."""
    for line in raw_output.split("\n"):
        if line.lower().startswith("explanation:"):
            return line[len("explanation:"):].strip()
    return raw_output


print("Functions loaded.")

Functions loaded.

## Step 2.1 — Test Draft Annotation Instructions

We run the annotation on a **random sample of 50 rows** from the translated dataset. This is equivalent to the `bacchuss()` call in the R vignette.

After running, visually inspect the results and note:
- Which cases were correctly labelled?
- Are there clear cases not described in your coding instructions?
- What are general problems with the instructions?

Then go back and update the `instructions` and `reminder` in the cell above.

In [44]:
# ── Config ───────────────────────────────────────────────────────────────
RESULTS_DIR = Path("results")
RESULTS_DIR.mkdir(exist_ok=True)

SAMPLE_SIZE_2_1 = 20000
RANDOM_SEED = 42

# Saving of full run result
OUTPUT_2_1 = RESULTS_DIR / f"annotation_step2_1_seed{RANDOM_SEED}_n{SAMPLE_SIZE_2_1}.csv"

# Separate continuous files for relevant cases makes it easier to define test set 
CRIME_FRAME_NEG = RESULTS_DIR / "crime_frame_neg.csv"
CRIME_FRAME_POS = RESULTS_DIR / "crime_frame_pos.csv"
UNCLEAR_FRAME = RESULTS_DIR / "unclear_frame.csv"

UNCLEAR_LABELS = ["UNCLEAR"]

# Manual testset later (n=500)
MANUAL_TESTSET = RESULTS_DIR / "manual_testset.csv"
# ─────────────────────────────────────────────────────────────────────────

df = pd.read_csv("dataset/all_multi_paragraphs_2022_2026.csv")
sample_2_1 = df.sample(n=SAMPLE_SIZE_2_1, random_state=RANDOM_SEED).copy().reset_index(drop=True)

print(f"Dataset loaded {len(df)} rows total")
print(f"Sample size {len(sample_2_1)} rows")
print("Running annotation at temperature=0.0 (deterministic)\n")

Dataset loaded 659895 rows total
Sample size 20000 rows
Running annotation at temperature=0.0 (deterministic)

In [45]:
# Sample from the full dataset
sample_2_1 = df.sample(
    n=SAMPLE_SIZE_2_1,
    random_state=RANDOM_SEED
).reset_index(drop=True)

In [46]:
results_2_1 = []

for i, row in sample_2_1.iterrows():
    raw = annotate(str(row["text_block"]), instructions, reminder, temperature=0.0)
    label = parse_label(raw)
    explanation = parse_explanation(raw)

    results_2_1.append({
        "article_id":    row["article_id"],
        "par_index":     row["par_index"],
        "group":         row["group"],
        "text_block_en": row["text_block"],
        "raw_output":    raw,
        "label":         label,
        "explanation":   explanation
    })

    if (i + 1) % 10 == 0:
        n_neg = sum(1 for r in results_2_1 if r["label"] == "CRIME_FRAME_NEG")
        n_pos = sum(1 for r in results_2_1 if r["label"] == "CRIME_FRAME_POS")
        n_unclear = sum(1 for r in results_2_1 if r["label"] == "UNCLEAR")

        print(
            f"  [{i+1}/{len(sample_2_1)}] done "
            f"NEG: {n_neg}, POS: {n_pos}, UNCLEAR: {n_unclear}"
        )

annotation_2_1 = pd.DataFrame(results_2_1)

# Save full Step 2.1 output only
annotation_2_1.to_csv(OUTPUT_2_1, index=False)

print(f"\nSaved Step 2.1 to {OUTPUT_2_1}")
print("\nDone!")
print(annotation_2_1["label"].value_counts())

crime_total = annotation_2_1["label"].isin(["CRIME_FRAME_NEG", "CRIME_FRAME_POS"]).sum()

print(f"\nAny CRIME_FRAME rate: {crime_total / len(annotation_2_1) * 100:.1f}%")
print(f"CRIME_FRAME_NEG rate: {(annotation_2_1['label'] == 'CRIME_FRAME_NEG').mean() * 100:.1f}%")
print(f"CRIME_FRAME_POS rate: {(annotation_2_1['label'] == 'CRIME_FRAME_POS').mean() * 100:.1f}%")
print(f"NO_CRIME_FRAME rate: {(annotation_2_1['label'] == 'NO_CRIME_FRAME').mean() * 100:.1f}%")
print(f"UNCLEAR rate: {(annotation_2_1['label'] == 'UNCLEAR').mean() * 100:.1f}%")

  [10/20000] done NEG: 1, POS: 0, UNCLEAR: 0
  [20/20000] done NEG: 2, POS: 0, UNCLEAR: 0
  [30/20000] done NEG: 2, POS: 0, UNCLEAR: 0
  [40/20000] done NEG: 3, POS: 0, UNCLEAR: 0
  [50/20000] done NEG: 3, POS: 0, UNCLEAR: 0
  [60/20000] done NEG: 4, POS: 0, UNCLEAR: 0
  [70/20000] done NEG: 4, POS: 0, UNCLEAR: 0
  [80/20000] done NEG: 6, POS: 0, UNCLEAR: 0
  [90/20000] done NEG: 7, POS: 0, UNCLEAR: 0
  [100/20000] done NEG: 8, POS: 0, UNCLEAR: 0
  [110/20000] done NEG: 8, POS: 0, UNCLEAR: 0
  [120/20000] done NEG: 9, POS: 0, UNCLEAR: 0
  [130/20000] done NEG: 9, POS: 0, UNCLEAR: 0
  [140/20000] done NEG: 9, POS: 0, UNCLEAR: 0
  [150/20000] done NEG: 9, POS: 0, UNCLEAR: 0
  [160/20000] done NEG: 9, POS: 0, UNCLEAR: 0
  [170/20000] done NEG: 9, POS: 0, UNCLEAR: 0
  [180/20000] done NEG: 9, POS: 0, UNCLEAR: 0
  [190/20000] done NEG: 9, POS: 0, UNCLEAR: 0
  [200/20000] done NEG: 9, POS: 0, UNCLEAR: 0
  [210/20000] done NEG: 9, POS: 0, UNCLEAR: 0
  [220/20000] done NEG: 10, POS: 0, UNCLEAR: 0
  [230/20000] done NEG: 10, POS: 0, UNCLEAR: 0
  [240/20000] done NEG: 11, POS: 0, UNCLEAR: 0
  [250/20000] done NEG: 11, POS: 0, UNCLEAR: 0
  [260/20000] done NEG: 11, POS: 0, UNCLEAR: 0
  [270/20000] done NEG: 11, POS: 0, UNCLEAR: 0
  [280/20000] done NEG: 12, POS: 0, UNCLEAR: 0
  [290/20000] done NEG: 13, POS: 0, UNCLEAR: 0
  [300/20000] done NEG: 13, POS: 0, UNCLEAR: 0
  [310/20000] done NEG: 13, POS: 0, UNCLEAR: 0
  [320/20000] done NEG: 13, POS: 0, UNCLEAR: 0
  [330/20000] done NEG: 13, POS: 0, UNCLEAR: 0
  [340/20000] done NEG: 14, POS: 0, UNCLEAR: 0
  [350/20000] done NEG: 14, POS: 0, UNCLEAR: 0
  [360/20000] done NEG: 14, POS: 0, UNCLEAR: 0
  [370/20000] done NEG: 15, POS: 0, UNCLEAR: 0
  [380/20000] done NEG: 15, POS: 1, UNCLEAR: 0
  [390/20000] done NEG: 16, POS: 1, UNCLEAR: 0
  [400/20000] done NEG: 18, POS: 1, UNCLEAR: 0
  [410/20000] done NEG: 19, POS: 1, UNCLEAR: 0
  [420/20000] done NEG: 22, POS: 1, UNCLEAR: 0
  [430/20000] done NEG: 22, POS: 1, UNCLEAR: 0
  [440/20000] done NEG: 25, POS: 1, UNCLEAR: 0
  [450/20000] done NEG: 25, POS: 1, UNCLEAR: 0
  [460/20000] done NEG: 26, POS: 1, UNCLEAR: 0
  [470/20000] done NEG: 26, POS: 1, UNCLEAR: 0
  [480/20000] done NEG: 27, POS: 1, UNCLEAR: 0
  [490/20000] done NEG: 28, POS: 1, UNCLEAR: 0
  [500/20000] done NEG: 28, POS: 1, UNCLEAR: 0
  [510/20000] done NEG: 29, POS: 1, UNCLEAR: 0
  [520/20000] done NEG: 29, POS: 1, UNCLEAR: 0
  [530/20000] done NEG: 29, POS: 1, UNCLEAR: 0
  [540/20000] done NEG: 29, POS: 1, UNCLEAR: 0
  [550/20000] done NEG: 31, POS: 1, UNCLEAR: 0
  [560/20000] done NEG: 32, POS: 1, UNCLEAR: 0
  [570/20000] done NEG: 33, POS: 1, UNCLEAR: 0
  [580/20000] done NEG: 34, POS: 1, UNCLEAR: 0
  [590/20000] done NEG: 36, POS: 1, UNCLEAR: 0
  [600/20000] done NEG: 36, POS: 1, UNCLEAR: 0
  [610/20000] done NEG: 37, POS: 1, UNCLEAR: 0
  [620/20000] done NEG: 37, POS: 1, UNCLEAR: 0
  [630/20000] done NEG: 38, POS: 1, UNCLEAR: 0
  [640/20000] done NEG: 38, POS: 1, UNCLEAR: 0
  [650/20000] done NEG: 39, POS: 1, UNCLEAR: 0
  [660/20000] done NEG: 39, POS: 1, UNCLEAR: 0
  [670/20000] done NEG: 39, POS: 1, UNCLEAR: 0
  [680/20000] done NEG: 40, POS: 1, UNCLEAR: 0
  [690/20000] done NEG: 40, POS: 1, UNCLEAR: 0
  [700/20000] done NEG: 40, POS: 1, UNCLEAR: 0
  [710/20000] done NEG: 41, POS: 1, UNCLEAR: 0
  [720/20000] done NEG: 42, POS: 1, UNCLEAR: 0
  [730/20000] done NEG: 42, POS: 1, UNCLEAR: 0
  [740/20000] done NEG: 43, POS: 1, UNCLEAR: 0
  [750/20000] done NEG: 43, POS: 1, UNCLEAR: 0
  [760/20000] done NEG: 44, POS: 1, UNCLEAR: 0
  [770/20000] done NEG: 44, POS: 1, UNCLEAR: 0
  [780/20000] done NEG: 44, POS: 1, UNCLEAR: 0
  [790/20000] done NEG: 44, POS: 1, UNCLEAR: 0
  [800/20000] done NEG: 44, POS: 1, UNCLEAR: 0
  [810/20000] done NEG: 44, POS: 1, UNCLEAR: 0
  [820/20000] done NEG: 45, POS: 1, UNCLEAR: 0
  [830/20000] done NEG: 45, POS: 1, UNCLEAR: 0
  [840/20000] done NEG: 45, POS: 1, UNCLEAR: 0
  [850/20000] done NEG: 45, POS: 1, UNCLEAR: 0
  [860/20000] done NEG: 47, POS: 1, UNCLEAR: 0
  [870/20000] done NEG: 48, POS: 1, UNCLEAR: 0
  [880/20000] done NEG: 48, POS: 1, UNCLEAR: 0
  [890/20000] done NEG: 49, POS: 1, UNCLEAR: 0
  [900/20000] done NEG: 50, POS: 1, UNCLEAR: 0
  [910/20000] done NEG: 51, POS: 1, UNCLEAR: 0
  [920/20000] done NEG: 51, POS: 1, UNCLEAR: 0
  [930/20000] done NEG: 51, POS: 1, UNCLEAR: 0
  [940/20000] done NEG: 51, POS: 1, UNCLEAR: 0
  [950/20000] done NEG: 51, POS: 1, UNCLEAR: 0
  [960/20000] done NEG: 52, POS: 1, UNCLEAR: 0
  [970/20000] done NEG: 52, POS: 1, UNCLEAR: 0
  [980/20000] done NEG: 53, POS: 1, UNCLEAR: 0
  [990/20000] done NEG: 54, POS: 1, UNCLEAR: 0
  [1000/20000] done NEG: 54, POS: 1, UNCLEAR: 0
  [1010/20000] done NEG: 55, POS: 1, UNCLEAR: 0
  [1020/20000] done NEG: 55, POS: 1, UNCLEAR: 0
  [1030/20000] done NEG: 55, POS: 1, UNCLEAR: 0
  [1040/20000] done NEG: 56, POS: 1, UNCLEAR: 0
  [1050/20000] done NEG: 56, POS: 1, UNCLEAR: 0
  [1060/20000] done NEG: 56, POS: 1, UNCLEAR: 0
  [1070/20000] done NEG: 58, POS: 1, UNCLEAR: 0
  [1080/20000] done NEG: 59, POS: 1, UNCLEAR: 0
  [1090/20000] done NEG: 59, POS: 1, UNCLEAR: 0
  [1100/20000] done NEG: 60, POS: 1, UNCLEAR: 0
  [1110/20000] done NEG: 61, POS: 1, UNCLEAR: 0
  [1120/20000] done NEG: 61, POS: 1, UNCLEAR: 0
  [1130/20000] done NEG: 62, POS: 1, UNCLEAR: 0
  [1140/20000] done NEG: 62, POS: 1, UNCLEAR: 0
  [1150/20000] done NEG: 62, POS: 1, UNCLEAR: 0
  [1160/20000] done NEG: 62, POS: 1, UNCLEAR: 0
  [1170/20000] done NEG: 62, POS: 1, UNCLEAR: 0
  [1180/20000] done NEG: 62, POS: 1, UNCLEAR: 0
  [1190/20000] done NEG: 62, POS: 1, UNCLEAR: 0
  [1200/20000] done NEG: 62, POS: 1, UNCLEAR: 0
  [1210/20000] done NEG: 64, POS: 1, UNCLEAR: 0
  [1220/20000] done NEG: 64, POS: 1, UNCLEAR: 0
  [1230/20000] done NEG: 64, POS: 1, UNCLEAR: 0
  [1240/20000] done NEG: 65, POS: 1, UNCLEAR: 0
  [1250/20000] done NEG: 65, POS: 1, UNCLEAR: 0
  [1260/20000] done NEG: 66, POS: 1, UNCLEAR: 0
  [1270/20000] done NEG: 66, POS: 1, UNCLEAR: 0
  [1280/20000] done NEG: 66, POS: 1, UNCLEAR: 0
  [1290/20000] done NEG: 66, POS: 1, UNCLEAR: 0
  [1300/20000] done NEG: 67, POS: 1, UNCLEAR: 0
  [1310/20000] done NEG: 68, POS: 1, UNCLEAR: 0
  [1320/20000] done NEG: 68, POS: 1, UNCLEAR: 0
  [1330/20000] done NEG: 68, POS: 1, UNCLEAR: 0
  [1340/20000] done NEG: 68, POS: 1, UNCLEAR: 0
  [1350/20000] done NEG: 69, POS: 1, UNCLEAR: 0
  [1360/20000] done NEG: 69, POS: 1, UNCLEAR: 0
  [1370/20000] done NEG: 69, POS: 1, UNCLEAR: 0
  [1380/20000] done NEG: 69, POS: 1, UNCLEAR: 0
  [1390/20000] done NEG: 69, POS: 1, UNCLEAR: 0
  [1400/20000] done NEG: 69, POS: 1, UNCLEAR: 0
  [1410/20000] done NEG: 70, POS: 1, UNCLEAR: 0
  [1420/20000] done NEG: 70, POS: 1, UNCLEAR: 0
  [1430/20000] done NEG: 70, POS: 1, UNCLEAR: 0
  [1440/20000] done NEG: 70, POS: 1, UNCLEAR: 0
  [1450/20000] done NEG: 71, POS: 1, UNCLEAR: 0
  [1460/20000] done NEG: 72, POS: 1, UNCLEAR: 0
  [1470/20000] done NEG: 72, POS: 1, UNCLEAR: 0
  [1480/20000] done NEG: 72, POS: 1, UNCLEAR: 0
  [1490/20000] done NEG: 73, POS: 1, UNCLEAR: 0
  [1500/20000] done NEG: 73, POS: 1, UNCLEAR: 0
  [1510/20000] done NEG: 73, POS: 1, UNCLEAR: 0
  [1520/20000] done NEG: 74, POS: 1, UNCLEAR: 0
  [1530/20000] done NEG: 74, POS: 1, UNCLEAR: 0
  [1540/20000] done NEG: 75, POS: 1, UNCLEAR: 0
  [1550/20000] done NEG: 75, POS: 1, UNCLEAR: 0
  [1560/20000] done NEG: 75, POS: 1, UNCLEAR: 0
  [1570/20000] done NEG: 75, POS: 1, UNCLEAR: 0
  [1580/20000] done NEG: 76, POS: 1, UNCLEAR: 0
  [1590/20000] done NEG: 77, POS: 1, UNCLEAR: 0
  [1600/20000] done NEG: 77, POS: 1, UNCLEAR: 0
  [1610/20000] done NEG: 77, POS: 1, UNCLEAR: 0
  [1620/20000] done NEG: 77, POS: 1, UNCLEAR: 0
  [1630/20000] done NEG: 78, POS: 1, UNCLEAR: 0
  [1640/20000] done NEG: 78, POS: 1, UNCLEAR: 0
  [1650/20000] done NEG: 78, POS: 1, UNCLEAR: 0
  [1660/20000] done NEG: 78, POS: 1, UNCLEAR: 0
  [1670/20000] done NEG: 79, POS: 1, UNCLEAR: 0
  [1680/20000] done NEG: 80, POS: 1, UNCLEAR: 0
  [1690/20000] done NEG: 80, POS: 1, UNCLEAR: 0
  [1700/20000] done NEG: 81, POS: 1, UNCLEAR: 0
  [1710/20000] done NEG: 82, POS: 1, UNCLEAR: 0
  [1720/20000] done NEG: 82, POS: 1, UNCLEAR: 0
  [1730/20000] done NEG: 83, POS: 1, UNCLEAR: 0
  [1740/20000] done NEG: 83, POS: 1, UNCLEAR: 0
  [1750/20000] done NEG: 83, POS: 1, UNCLEAR: 0
  [1760/20000] done NEG: 83, POS: 1, UNCLEAR: 0
  [1770/20000] done NEG: 83, POS: 1, UNCLEAR: 0
  [1780/20000] done NEG: 83, POS: 1, UNCLEAR: 0
  [1790/20000] done NEG: 83, POS: 1, UNCLEAR: 0
  [1800/20000] done NEG: 83, POS: 1, UNCLEAR: 0
  [1810/20000] done NEG: 83, POS: 1, UNCLEAR: 0
  [1820/20000] done NEG: 83, POS: 1, UNCLEAR: 0
  [1830/20000] done NEG: 84, POS: 1, UNCLEAR: 0
  [1840/20000] done NEG: 85, POS: 1, UNCLEAR: 0
  [1850/20000] done NEG: 85, POS: 1, UNCLEAR: 0
  [1860/20000] done NEG: 85, POS: 1, UNCLEAR: 0
  [1870/20000] done NEG: 86, POS: 1, UNCLEAR: 0
  [1880/20000] done NEG: 86, POS: 1, UNCLEAR: 0
  [1890/20000] done NEG: 86, POS: 1, UNCLEAR: 0
  [1900/20000] done NEG: 87, POS: 1, UNCLEAR: 0
  [1910/20000] done NEG: 87, POS: 1, UNCLEAR: 0
  [1920/20000] done NEG: 87, POS: 1, UNCLEAR: 0
  [1930/20000] done NEG: 87, POS: 1, UNCLEAR: 0
  [1940/20000] done NEG: 87, POS: 1, UNCLEAR: 0
  [1950/20000] done NEG: 87, POS: 1, UNCLEAR: 0
  [1960/20000] done NEG: 87, POS: 1, UNCLEAR: 0
  [1970/20000] done NEG: 87, POS: 1, UNCLEAR: 0
  [1980/20000] done NEG: 87, POS: 1, UNCLEAR: 0
  [1990/20000] done NEG: 87, POS: 1, UNCLEAR: 0
  [2000/20000] done NEG: 87, POS: 1, UNCLEAR: 0
  [2010/20000] done NEG: 87, POS: 1, UNCLEAR: 0
  [2020/20000] done NEG: 90, POS: 1, UNCLEAR: 0
  [2030/20000] done NEG: 91, POS: 1, UNCLEAR: 0
  [2040/20000] done NEG: 92, POS: 1, UNCLEAR: 0
  [2050/20000] done NEG: 92, POS: 1, UNCLEAR: 0
  [2060/20000] done NEG: 93, POS: 1, UNCLEAR: 0
  [2070/20000] done NEG: 93, POS: 1, UNCLEAR: 0
  [2080/20000] done NEG: 93, POS: 1, UNCLEAR: 0
  [2090/20000] done NEG: 94, POS: 1, UNCLEAR: 0
  [2100/20000] done NEG: 94, POS: 1, UNCLEAR: 0
  [2110/20000] done NEG: 94, POS: 1, UNCLEAR: 0
  [2120/20000] done NEG: 94, POS: 1, UNCLEAR: 0
  [2130/20000] done NEG: 94, POS: 1, UNCLEAR: 0
  [2140/20000] done NEG: 95, POS: 1, UNCLEAR: 0
  [2150/20000] done NEG: 95, POS: 1, UNCLEAR: 0
  [2160/20000] done NEG: 95, POS: 1, UNCLEAR: 0
  [2170/20000] done NEG: 96, POS: 1, UNCLEAR: 0
  [2180/20000] done NEG: 96, POS: 1, UNCLEAR: 0
  [2190/20000] done NEG: 97, POS: 1, UNCLEAR: 0
  [2200/20000] done NEG: 97, POS: 1, UNCLEAR: 0
  [2210/20000] done NEG: 97, POS: 1, UNCLEAR: 0
  [2220/20000] done NEG: 98, POS: 1, UNCLEAR: 0
  [2230/20000] done NEG: 98, POS: 1, UNCLEAR: 0
  [2240/20000] done NEG: 98, POS: 1, UNCLEAR: 0
  [2250/20000] done NEG: 98, POS: 1, UNCLEAR: 0
  [2260/20000] done NEG: 98, POS: 1, UNCLEAR: 0
  [2270/20000] done NEG: 98, POS: 1, UNCLEAR: 0
  [2280/20000] done NEG: 98, POS: 1, UNCLEAR: 0
  [2290/20000] done NEG: 99, POS: 1, UNCLEAR: 0
  [2300/20000] done NEG: 100, POS: 1, UNCLEAR: 0
  [2310/20000] done NEG: 100, POS: 1, UNCLEAR: 0
  [2320/20000] done NEG: 100, POS: 1, UNCLEAR: 0
  [2330/20000] done NEG: 100, POS: 1, UNCLEAR: 0
  [2340/20000] done NEG: 100, POS: 1, UNCLEAR: 0
  [2350/20000] done NEG: 100, POS: 1, UNCLEAR: 0
  [2360/20000] done NEG: 102, POS: 1, UNCLEAR: 0
  [2370/20000] done NEG: 102, POS: 1, UNCLEAR: 0
  [2380/20000] done NEG: 103, POS: 1, UNCLEAR: 0
  [2390/20000] done NEG: 103, POS: 1, UNCLEAR: 0
  [2400/20000] done NEG: 103, POS: 1, UNCLEAR: 0
  [2410/20000] done NEG: 103, POS: 1, UNCLEAR: 0
  [2420/20000] done NEG: 103, POS: 1, UNCLEAR: 0
  [2430/20000] done NEG: 103, POS: 1, UNCLEAR: 0
  [2440/20000] done NEG: 103, POS: 1, UNCLEAR: 0
  [2450/20000] done NEG: 103, POS: 1, UNCLEAR: 0
  [2460/20000] done NEG: 103, POS: 1, UNCLEAR: 0
  [2470/20000] done NEG: 104, POS: 1, UNCLEAR: 0
  [2480/20000] done NEG: 104, POS: 1, UNCLEAR: 0
  [2490/20000] done NEG: 105, POS: 1, UNCLEAR: 0
  [2500/20000] done NEG: 106, POS: 1, UNCLEAR: 0
  [2510/20000] done NEG: 107, POS: 1, UNCLEAR: 0
  [2520/20000] done NEG: 107, POS: 1, UNCLEAR: 0
  [2530/20000] done NEG: 108, POS: 1, UNCLEAR: 0
  [2540/20000] done NEG: 108, POS: 1, UNCLEAR: 0
  [2550/20000] done NEG: 109, POS: 1, UNCLEAR: 0
  [2560/20000] done NEG: 109, POS: 2, UNCLEAR: 0
  [2570/20000] done NEG: 109, POS: 2, UNCLEAR: 0
  [2580/20000] done NEG: 110, POS: 2, UNCLEAR: 0
  [2590/20000] done NEG: 110, POS: 2, UNCLEAR: 0
  [2600/20000] done NEG: 111, POS: 2, UNCLEAR: 0
  [2610/20000] done NEG: 111, POS: 2, UNCLEAR: 0
  [2620/20000] done NEG: 112, POS: 2, UNCLEAR: 0
  [2630/20000] done NEG: 112, POS: 2, UNCLEAR: 0
  [2640/20000] done NEG: 112, POS: 2, UNCLEAR: 0
  [2650/20000] done NEG: 112, POS: 2, UNCLEAR: 0
  [2660/20000] done NEG: 112, POS: 2, UNCLEAR: 0
  [2670/20000] done NEG: 112, POS: 2, UNCLEAR: 0
  [2680/20000] done NEG: 112, POS: 2, UNCLEAR: 0
  [2690/20000] done NEG: 112, POS: 2, UNCLEAR: 0
  [2700/20000] done NEG: 112, POS: 2, UNCLEAR: 0
  [2710/20000] done NEG: 112, POS: 2, UNCLEAR: 0
  [2720/20000] done NEG: 114, POS: 2, UNCLEAR: 0
  [2730/20000] done NEG: 115, POS: 2, UNCLEAR: 0
  [2740/20000] done NEG: 117, POS: 2, UNCLEAR: 0
  [2750/20000] done NEG: 117, POS: 2, UNCLEAR: 0
  [2760/20000] done NEG: 118, POS: 2, UNCLEAR: 0
  [2770/20000] done NEG: 118, POS: 2, UNCLEAR: 0
  [2780/20000] done NEG: 119, POS: 2, UNCLEAR: 0
  [2790/20000] done NEG: 119, POS: 2, UNCLEAR: 0
  [2800/20000] done NEG: 120, POS: 2, UNCLEAR: 0
  [2810/20000] done NEG: 122, POS: 2, UNCLEAR: 0
  [2820/20000] done NEG: 123, POS: 2, UNCLEAR: 0
  [2830/20000] done NEG: 123, POS: 2, UNCLEAR: 0
  [2840/20000] done NEG: 124, POS: 2, UNCLEAR: 0
  [2850/20000] done NEG: 125, POS: 2, UNCLEAR: 0
  [2860/20000] done NEG: 126, POS: 2, UNCLEAR: 0
  [2870/20000] done NEG: 126, POS: 2, UNCLEAR: 0
  [2880/20000] done NEG: 126, POS: 2, UNCLEAR: 0
  [2890/20000] done NEG: 126, POS: 2, UNCLEAR: 0
  [2900/20000] done NEG: 126, POS: 2, UNCLEAR: 0
  [2910/20000] done NEG: 126, POS: 2, UNCLEAR: 0
  [2920/20000] done NEG: 126, POS: 2, UNCLEAR: 0
  [2930/20000] done NEG: 128, POS: 2, UNCLEAR: 0
  [2940/20000] done NEG: 129, POS: 2, UNCLEAR: 0
  [2950/20000] done NEG: 130, POS: 2, UNCLEAR: 0
  [2960/20000] done NEG: 130, POS: 2, UNCLEAR: 0
  [2970/20000] done NEG: 131, POS: 2, UNCLEAR: 0
  [2980/20000] done NEG: 131, POS: 2, UNCLEAR: 0
  [2990/20000] done NEG: 131, POS: 2, UNCLEAR: 0
  [3000/20000] done NEG: 133, POS: 2, UNCLEAR: 0
  [3010/20000] done NEG: 133, POS: 2, UNCLEAR: 0
  [3020/20000] done NEG: 133, POS: 2, UNCLEAR: 0
  [3030/20000] done NEG: 134, POS: 2, UNCLEAR: 0
  [3040/20000] done NEG: 135, POS: 2, UNCLEAR: 0
  [3050/20000] done NEG: 135, POS: 2, UNCLEAR: 0
  [3060/20000] done NEG: 135, POS: 2, UNCLEAR: 0
  [3070/20000] done NEG: 135, POS: 2, UNCLEAR: 0
  [3080/20000] done NEG: 137, POS: 2, UNCLEAR: 0
  [3090/20000] done NEG: 137, POS: 2, UNCLEAR: 0
  [3100/20000] done NEG: 137, POS: 2, UNCLEAR: 0
  [3110/20000] done NEG: 137, POS: 2, UNCLEAR: 0
  [3120/20000] done NEG: 137, POS: 2, UNCLEAR: 0
  [3130/20000] done NEG: 137, POS: 2, UNCLEAR: 0
  [3140/20000] done NEG: 137, POS: 2, UNCLEAR: 0
  [3150/20000] done NEG: 138, POS: 2, UNCLEAR: 0
  [3160/20000] done NEG: 138, POS: 2, UNCLEAR: 0
  [3170/20000] done NEG: 139, POS: 2, UNCLEAR: 0
  [3180/20000] done NEG: 139, POS: 2, UNCLEAR: 0
  [3190/20000] done NEG: 139, POS: 2, UNCLEAR: 0
  [3200/20000] done NEG: 140, POS: 2, UNCLEAR: 0
  [3210/20000] done NEG: 140, POS: 2, UNCLEAR: 0
  [3220/20000] done NEG: 140, POS: 2, UNCLEAR: 0
  [3230/20000] done NEG: 141, POS: 2, UNCLEAR: 0
  [3240/20000] done NEG: 141, POS: 2, UNCLEAR: 0
  [3250/20000] done NEG: 141, POS: 2, UNCLEAR: 0
  [3260/20000] done NEG: 141, POS: 2, UNCLEAR: 0
  [3270/20000] done NEG: 141, POS: 2, UNCLEAR: 0
  [3280/20000] done NEG: 141, POS: 2, UNCLEAR: 0
  [3290/20000] done NEG: 141, POS: 2, UNCLEAR: 0
  [3300/20000] done NEG: 141, POS: 2, UNCLEAR: 0
  [3310/20000] done NEG: 141, POS: 2, UNCLEAR: 0
  [3320/20000] done NEG: 141, POS: 2, UNCLEAR: 0
  [3330/20000] done NEG: 142, POS: 2, UNCLEAR: 0
  [3340/20000] done NEG: 142, POS: 2, UNCLEAR: 0
  [3350/20000] done NEG: 144, POS: 2, UNCLEAR: 0
  [3360/20000] done NEG: 145, POS: 2, UNCLEAR: 0
  [3370/20000] done NEG: 146, POS: 2, UNCLEAR: 0
  [3380/20000] done NEG: 147, POS: 2, UNCLEAR: 0
  [3390/20000] done NEG: 147, POS: 2, UNCLEAR: 0
  [3400/20000] done NEG: 147, POS: 2, UNCLEAR: 0
  [3410/20000] done NEG: 147, POS: 2, UNCLEAR: 0
  [3420/20000] done NEG: 148, POS: 2, UNCLEAR: 0
  [3430/20000] done NEG: 148, POS: 2, UNCLEAR: 0
  [3440/20000] done NEG: 148, POS: 2, UNCLEAR: 0
  [3450/20000] done NEG: 149, POS: 2, UNCLEAR: 0
  [3460/20000] done NEG: 150, POS: 2, UNCLEAR: 0
  [3470/20000] done NEG: 150, POS: 2, UNCLEAR: 0
  [3480/20000] done NEG: 150, POS: 2, UNCLEAR: 0
  [3490/20000] done NEG: 151, POS: 2, UNCLEAR: 0
  [3500/20000] done NEG: 151, POS: 2, UNCLEAR: 0
  [3510/20000] done NEG: 151, POS: 2, UNCLEAR: 0
  [3520/20000] done NEG: 152, POS: 2, UNCLEAR: 0
  [3530/20000] done NEG: 153, POS: 2, UNCLEAR: 0
  [3540/20000] done NEG: 154, POS: 2, UNCLEAR: 0
  [3550/20000] done NEG: 156, POS: 2, UNCLEAR: 0
  [3560/20000] done NEG: 157, POS: 2, UNCLEAR: 0
  [3570/20000] done NEG: 157, POS: 2, UNCLEAR: 0
  [3580/20000] done NEG: 157, POS: 2, UNCLEAR: 0
  [3590/20000] done NEG: 157, POS: 2, UNCLEAR: 0
  [3600/20000] done NEG: 157, POS: 2, UNCLEAR: 0
  [3610/20000] done NEG: 158, POS: 2, UNCLEAR: 0
  [3620/20000] done NEG: 158, POS: 2, UNCLEAR: 0
  [3630/20000] done NEG: 158, POS: 2, UNCLEAR: 0
  [3640/20000] done NEG: 158, POS: 2, UNCLEAR: 0
  [3650/20000] done NEG: 158, POS: 2, UNCLEAR: 0
  [3660/20000] done NEG: 158, POS: 2, UNCLEAR: 0
  [3670/20000] done NEG: 158, POS: 2, UNCLEAR: 0
  [3680/20000] done NEG: 159, POS: 2, UNCLEAR: 0
  [3690/20000] done NEG: 160, POS: 2, UNCLEAR: 0
  [3700/20000] done NEG: 160, POS: 2, UNCLEAR: 0
  [3710/20000] done NEG: 160, POS: 2, UNCLEAR: 0
  [3720/20000] done NEG: 162, POS: 2, UNCLEAR: 0
  [3730/20000] done NEG: 163, POS: 2, UNCLEAR: 0
  [3740/20000] done NEG: 164, POS: 2, UNCLEAR: 0
  [3750/20000] done NEG: 164, POS: 2, UNCLEAR: 0
  [3760/20000] done NEG: 164, POS: 2, UNCLEAR: 0
  [3770/20000] done NEG: 164, POS: 2, UNCLEAR: 0
  [3780/20000] done NEG: 165, POS: 2, UNCLEAR: 0
  [3790/20000] done NEG: 165, POS: 2, UNCLEAR: 0
  [3800/20000] done NEG: 165, POS: 2, UNCLEAR: 0
  [3810/20000] done NEG: 166, POS: 2, UNCLEAR: 0
  [3820/20000] done NEG: 166, POS: 2, UNCLEAR: 0
  [3830/20000] done NEG: 166, POS: 2, UNCLEAR: 0
  [3840/20000] done NEG: 166, POS: 2, UNCLEAR: 0
  [3850/20000] done NEG: 166, POS: 2, UNCLEAR: 0
  [3860/20000] done NEG: 168, POS: 2, UNCLEAR: 0
  [3870/20000] done NEG: 168, POS: 2, UNCLEAR: 0
  [3880/20000] done NEG: 170, POS: 2, UNCLEAR: 0
  [3890/20000] done NEG: 172, POS: 2, UNCLEAR: 0
  [3900/20000] done NEG: 172, POS: 2, UNCLEAR: 0
  [3910/20000] done NEG: 172, POS: 2, UNCLEAR: 0
  [3920/20000] done NEG: 172, POS: 2, UNCLEAR: 0
  [3930/20000] done NEG: 173, POS: 2, UNCLEAR: 0
  [3940/20000] done NEG: 173, POS: 2, UNCLEAR: 0
  [3950/20000] done NEG: 173, POS: 2, UNCLEAR: 0
  [3960/20000] done NEG: 173, POS: 2, UNCLEAR: 0
  [3970/20000] done NEG: 173, POS: 2, UNCLEAR: 0
  [3980/20000] done NEG: 174, POS: 2, UNCLEAR: 0
  [3990/20000] done NEG: 174, POS: 2, UNCLEAR: 0
  [4000/20000] done NEG: 174, POS: 2, UNCLEAR: 0
  [4010/20000] done NEG: 174, POS: 2, UNCLEAR: 0
  [4020/20000] done NEG: 174, POS: 2, UNCLEAR: 0
  [4030/20000] done NEG: 174, POS: 2, UNCLEAR: 0
  [4040/20000] done NEG: 176, POS: 2, UNCLEAR: 0
  [4050/20000] done NEG: 176, POS: 2, UNCLEAR: 0
  [4060/20000] done NEG: 177, POS: 2, UNCLEAR: 0
  [4070/20000] done NEG: 179, POS: 2, UNCLEAR: 0
  [4080/20000] done NEG: 179, POS: 2, UNCLEAR: 0
  [4090/20000] done NEG: 180, POS: 2, UNCLEAR: 0
  [4100/20000] done NEG: 180, POS: 2, UNCLEAR: 0
  [4110/20000] done NEG: 180, POS: 2, UNCLEAR: 0
  [4120/20000] done NEG: 180, POS: 2, UNCLEAR: 0
  [4130/20000] done NEG: 181, POS: 2, UNCLEAR: 0
  [4140/20000] done NEG: 181, POS: 2, UNCLEAR: 0
  [4150/20000] done NEG: 182, POS: 2, UNCLEAR: 0

### Inspect Results

Check the label distribution and flag any `UNCLEAR` labels (label drift). If more than **5% of labels are UNCLEAR**, adjust the reminder and output format instructions and rerun.

Use the output below to visually inspect cases — especially CRIME_FRAME cases — and ask:
- Does the label match what you would expect?
- Are there edge cases your instructions don't cover yet?

In [47]:
# Label distribution
total = len(annotation_2_1)
print("=== Label Distribution ===")
for label, count in annotation_2_1["label"].value_counts().items():
    print(f"  {label}: {count} ({count/total*100:.1f}%)")

# Flag unclear labels
unclear = annotation_2_1[annotation_2_1["label"] == "UNCLEAR"]

if len(unclear) > 0:
    pct = len(unclear) / total * 100
    print(f"\nUNCLEAR labels: {len(unclear)} ({pct:.1f}%)")

    if pct > 5:
        print("   → More than 5% unclear. Consider adjusting the reminder and output format.")
else:
    print("\n✓ No unclear labels.")

=== Label Distribution ===
  NO_CRIME_FRAME: 19144 (95.7%)
  CRIME_FRAME_NEG: 839 (4.2%)
  CRIME_FRAME_POS: 17 (0.1%)

✓ No unclear labels.

In [48]:
# Browse all results — sort by label for easier inspection
annotation_2_1[
    ["group", "label", "explanation", "text_block_en"]
].sort_values("label")

,group,label,explanation,text_block_en
12751,RUS,CRIME_FRAME_NEG,Die **[Gruppe 1]** wird explizit als Täterin d...,Zerstörter russischer Panzer\n\n„Zehn Zivilist...
14236,UKR,CRIME_FRAME_NEG,Die Gruppe wird explizit als potenzielle Quell...,In Belgorod und anderen Orten Russlands häufen...
6020,REFUG,CRIME_FRAME_NEG,Der Absatz verknüpft explizit die **illegale E...,Die illegalen Einreisen von [Gruppe 1] im Herb...
903,AZE,CRIME_FRAME_NEG,Der Absatz verknüpft die **[Gruppe 1]** expliz...,Im Mordprozess um den sogenannten Axtmörder vo...
13208,RUS,CRIME_FRAME_NEG,Der Absatz verknüpft explizit **[Gruppe 1]** m...,Die Firma soll demnach schon 2019 versucht hab...
...,...,...,...,...
6811,REFUG,NO_CRIME_FRAME,Der Absatz thematisiert ausschließlich gesundh...,Derzeit arbeite das Gesundheitsamt gemeinsam m...
6810,ROU,NO_CRIME_FRAME,Der Absatz thematisiert ausschließlich logisti...,\n\nSchwierigkeiten auf allen Wegen Ukrainisch...
6809,ESP,NO_CRIME_FRAME,"Der Absatz erwähnt weder Kriminalität, Sicherh...",Paris - Der Senegalese erhielt den Preis und w...
6816,REFUG,NO_CRIME_FRAME,Der Absatz erwähnt zwar Kriminalität (Festnahm...,Wegen Freundschaft mit Putin: Putin-Freund: Di...
19999,USA,NO_CRIME_FRAME,Der Absatz thematisiert einen geopolitischen K...,3. Russland kämpft gegen die ganze westliche W...

In [49]:
# Show only crime frame cases for focused inspection
crime_cases = annotation_2_1[
    annotation_2_1["label"].isin(["CRIME_FRAME_NEG", "CRIME_FRAME_POS"])
]

print(f"Crime frame cases: {len(crime_cases)}")

crime_cases[
    ["group", "label", "explanation", "text_block_en"]
].sort_values("label")

Crime frame cases: 856

,group,label,explanation,text_block_en
3,MIGR,CRIME_FRAME_NEG,Der Absatz verknüpft explizit die **[Gruppe 1]...,[Andere Gruppe] entsorgen eigene Papiere\n\nDi...
13273,ISLMST,CRIME_FRAME_NEG,Die Taliban werden explizit als **Terrorbewegu...,Die Taliban drohen den USA nach der Tötung des...
13341,AUT,CRIME_FRAME_NEG,Die Gruppe wird explizit als Täterin von Straf...,Eine 23-jährige [Gruppe 1] soll etliche PCR-Te...
13343,ASYL,CRIME_FRAME_NEG,Der Absatz verknüpft die **[Gruppe 1]** expliz...,Erinnerungen an den Fall in Freiburg\n\nDer „T...
13356,RUS,CRIME_FRAME_NEG,Die **[Gruppe 1]** wird explizit als Akteur da...,Wie schnell nach dem 24. Februar begannen die ...
...,...,...,...,...
11380,REFUG,CRIME_FRAME_POS,Der Absatz beschreibt präventive Maßnahmen (Ge...,Durch diese Kooperation seien seit der Gründun...
13675,REFUG,CRIME_FRAME_POS,Der Absatz thematisiert explizit **Präventions...,"Martin Dulig (SPD), Wirtschaftsminister von Sa..."
13705,ASYL,CRIME_FRAME_POS,Der Absatz verknüpft explizit die Gruppe mit *...,"Oft sind es politische Vorbilder, die einen in..."
377,MUSL,CRIME_FRAME_POS,Der Absatz verknüpft die Gruppe explizit mit *...,"Was könnte helfen, damit diese Männer sich bes..."
2556,RUS,CRIME_FRAME_POS,Die **[Gruppe 1]** wird explizit als **aktiver...,Die in der Bevölkerung rasant gewachsene Unpop...

In [50]:
# Save one-shot candidates from Step 2.1

crime_neg_cases = annotation_2_1[annotation_2_1["label"] == "CRIME_FRAME_NEG"].copy()
crime_pos_cases = annotation_2_1[annotation_2_1["label"] == "CRIME_FRAME_POS"].copy()
unclear_cases = annotation_2_1[annotation_2_1["label"] == "UNCLEAR"].copy()

for data in [crime_neg_cases, crime_pos_cases, unclear_cases]:
    data["seed"] = RANDOM_SEED
    data["sample_size"] = SAMPLE_SIZE_2_1
    data["source_step"] = "2.1_one_shot"

if CRIME_FRAME_NEG.exists():
    old_neg = pd.read_csv(CRIME_FRAME_NEG)
    crime_neg_cases = pd.concat([old_neg, crime_neg_cases], ignore_index=True)

crime_neg_cases = crime_neg_cases.drop_duplicates(subset=["article_id", "par_index"])
crime_neg_cases.to_csv(CRIME_FRAME_NEG, index=False)

if CRIME_FRAME_POS.exists():
    old_pos = pd.read_csv(CRIME_FRAME_POS)
    crime_pos_cases = pd.concat([old_pos, crime_pos_cases], ignore_index=True)

crime_pos_cases = crime_pos_cases.drop_duplicates(subset=["article_id", "par_index"])
crime_pos_cases.to_csv(CRIME_FRAME_POS, index=False)

if UNCLEAR_FRAME.exists():
    old_unclear = pd.read_csv(UNCLEAR_FRAME)
    unclear_cases = pd.concat([old_unclear, unclear_cases], ignore_index=True)

unclear_cases = unclear_cases.drop_duplicates(subset=["article_id", "par_index"])
unclear_cases.to_csv(UNCLEAR_FRAME, index=False)

print(f"Saved CRIME_FRAME_NEG cases to {CRIME_FRAME_NEG}")
print(f"Saved CRIME_FRAME_POS cases to {CRIME_FRAME_POS}")
print(f"Saved UNCLEAR cases to {UNCLEAR_FRAME}")

Saved CRIME_FRAME_NEG cases to results/crime_frame_neg.csv
Saved CRIME_FRAME_POS cases to results/crime_frame_pos.csv
Saved UNCLEAR cases to results/unclear_frame.csv

## Step 2.2 — Check for Hard Cases (briseus equivalent)

This step runs the annotation **multiple times with higher temperature** (0.7) on a subset of rows. Higher temperature introduces randomness — if the model consistently agrees with itself across runs, the case is clear. If it disagrees, the case is hard and the instructions need clarification.

This is the Python equivalent of the `briseus()` function from the `bacchuss` R package.

After running, sort by agreement (lowest first) and inspect the hard cases:
- Why is the model uncertain?
- Can you add a decision rule to resolve the ambiguity?
- Are these genuinely borderline cases, or a problem with the instructions?

> **Note:** This runs `n_runs × sample_size` API calls. With n_runs=5 and sample_size=20, that is 100 calls. Adjust accordingly.

In [52]:
# ── Config ───────────────────────────────────────────────────────────────
SAMPLE_SIZE_2_2 = 2000
N_RUNS = 10
TEMPERATURE = 0.7

# Seed only for selecting NO_CRIME_FRAME rows!
NO_CRIME_FILL_SEED = 99

HARD_CASES_FRAME = RESULTS_DIR / "hard_cases.csv"
OUTPUT_2_2 = RESULTS_DIR / f"annotation_step2_2_fillseed{NO_CRIME_FILL_SEED}_n{SAMPLE_SIZE_2_2}_runs{N_RUNS}.csv"
# ─────────────────────────────────────────────────────────────────────────

# Include all CRIME_FRAME_NEG, CRIME_FRAME_POS, and UNCLEAR cases from Step 2.1
interesting_cases = annotation_2_1[
    annotation_2_1["label"].isin(["CRIME_FRAME_NEG", "CRIME_FRAME_POS", "UNCLEAR"])
].copy()

# Fill remaining slots with NO_CRIME_FRAME cases
n_fill = SAMPLE_SIZE_2_2 - len(interesting_cases)

if n_fill > 0:
    no_crime_candidates = annotation_2_1[
        annotation_2_1["label"] == "NO_CRIME_FRAME"
    ].copy()

    no_crime_fill = no_crime_candidates.sample(
        n=min(n_fill, len(no_crime_candidates)),
        random_state=NO_CRIME_FILL_SEED
    ).copy()

    sample_2_2 = pd.concat([interesting_cases, no_crime_fill], ignore_index=True)
else:
    no_crime_fill = pd.DataFrame()
    sample_2_2 = interesting_cases.copy()

sample_2_2 = sample_2_2.drop_duplicates(
    subset=["article_id", "par_index"]
).reset_index(drop=True)

print(f"Interesting cases included: {len(interesting_cases)}")
print(f"NO_CRIME_FRAME fill cases included: {len(no_crime_fill)}")
print(f"Sample size: {len(sample_2_2)} rows")
print(f"Runs per paragraph: {N_RUNS}")
print(f"Total API calls: {len(sample_2_2) * N_RUNS}")
print(f"Temperature: {TEMPERATURE}")
print(sample_2_2["label"].value_counts())

Interesting cases included: 856
NO_CRIME_FRAME fill cases included: 1144
Sample size: 1998 rows
Runs per paragraph: 10
Total API calls: 19980
Temperature: 0.7
label
NO_CRIME_FRAME     1144
CRIME_FRAME_NEG     837
CRIME_FRAME_POS      17
Name: count, dtype: int64

In [61]:
results_2_2 = []

for i, row in sample_2_2.iterrows():
    text = str(row["text_block_en"])
    run_labels = [] 
    run_explanations = []

    for run in range(N_RUNS):
        raw = annotate(text, instructions, reminder, temperature=TEMPERATURE)
        run_labels.append(parse_label(raw))
        run_explanations.append(parse_explanation(raw))

    label_counts = Counter(run_labels)
    majority_label, majority_count = label_counts.most_common(1)[0]
    agreement = majority_count / N_RUNS

    result = { 
        "article_id": row["article_id"],
        "par_index": row["par_index"],
        "group": row["group"],
        "text_block_en": text,
        "step2_1_label": row["label"],
        "final_label": majority_label,
        "agreement": agreement,
    }

    for r, lbl in enumerate(run_labels):
        result[f"run_{r+1}"] = lbl
        result[f"explanation_{r+1}"] = run_explanations[r]

    results_2_2.append(result)

    print(
        f"  [{i+1}/{len(sample_2_2)}] "
        f"{majority_label} "
        f"(agreement: {agreement:.0%}) | runs: {run_labels}"
    )

annotation_2_2 = pd.DataFrame(results_2_2).sort_values("agreement").reset_index(drop=True)

annotation_2_2.to_csv(OUTPUT_2_2, index=False)

print(f"\nStep 2.2 complete. Saved to {OUTPUT_2_2}")
print(annotation_2_2["final_label"].value_counts())

  [1/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [2/1998] CRIME_FRAME_NEG (agreement: 50%) | runs: ['CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME']
  [3/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [4/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [5/1998] CRIME_FRAME_NEG (agreement: 60%) | runs: ['CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [6/1998] CRIME_FRAME_NEG (agreement: 90%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [7/1998] NO_CRIME_FRAME (agreement: 50%) | runs: ['NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [8/1998] CRIME_FRAME_NEG (agreement: 60%) | runs: ['NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [9/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [10/1998] CRIME_FRAME_NEG (agreement: 90%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [11/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [12/1998] CRIME_FRAME_NEG (agreement: 60%) | runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME']
  [13/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [14/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [15/1998] CRIME_FRAME_NEG (agreement: 70%) | runs: ['NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME']
  [16/1998] CRIME_FRAME_POS (agreement: 70%) | runs: ['CRIME_FRAME_POS', 'CRIME_FRAME_POS', 'CRIME_FRAME_POS', 'NO_CRIME_FRAME', 'CRIME_FRAME_POS', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_POS', 'CRIME_FRAME_POS', 'CRIME_FRAME_POS']
  [17/1998] CRIME_FRAME_NEG (agreement: 90%) | runs: ['CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [18/1998] CRIME_FRAME_NEG (agreement: 80%) | runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [19/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [20/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [21/1998] NO_CRIME_FRAME (agreement: 50%) | runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME']
  [22/1998] CRIME_FRAME_NEG (agreement: 70%) | runs: ['CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_POS', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [23/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [24/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [25/1998] CRIME_FRAME_NEG (agreement: 60%) | runs: ['NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME']
  [26/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [27/1998] CRIME_FRAME_NEG (agreement: 70%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG']
  [28/1998] CRIME_FRAME_NEG (agreement: 80%) | runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG']
  [29/1998] CRIME_FRAME_NEG (agreement: 60%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [30/1998] CRIME_FRAME_NEG (agreement: 70%) | runs: ['NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [31/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [32/1998] CRIME_FRAME_NEG (agreement: 70%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME']
  [33/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [34/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [35/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [36/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [37/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [38/1998] CRIME_FRAME_NEG (agreement: 70%) | runs: ['CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG']
  [39/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [40/1998] CRIME_FRAME_NEG (agreement: 60%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [41/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [42/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [43/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [44/1998] CRIME_FRAME_NEG (agreement: 60%) | runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [45/1998] CRIME_FRAME_NEG (agreement: 90%) | runs: ['CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [46/1998] CRIME_FRAME_NEG (agreement: 90%) | runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [47/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [48/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [49/1998] CRIME_FRAME_NEG (agreement: 80%) | runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [50/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [51/1998] CRIME_FRAME_NEG (agreement: 60%) | runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [52/1998] CRIME_FRAME_NEG (agreement: 70%) | runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [53/1998] CRIME_FRAME_NEG (agreement: 90%) | runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [54/1998] CRIME_FRAME_NEG (agreement: 90%) | runs: ['CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [55/1998] CRIME_FRAME_NEG (agreement: 90%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME']
  [56/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [57/1998] CRIME_FRAME_NEG (agreement: 90%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME']
  [58/1998] NO_CRIME_FRAME (agreement: 50%) | runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG']
  [59/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [60/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [61/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [62/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [63/1998] CRIME_FRAME_NEG (agreement: 60%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME']
  [64/1998] CRIME_FRAME_NEG (agreement: 60%) | runs: ['CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG']
  [65/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [66/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [67/1998] CRIME_FRAME_NEG (agreement: 90%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [68/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [69/1998] CRIME_FRAME_NEG (agreement: 90%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [70/1998] CRIME_FRAME_NEG (agreement: 70%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG']
  [71/1998] CRIME_FRAME_NEG (agreement: 90%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [72/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [73/1998] CRIME_FRAME_NEG (agreement: 70%) | runs: ['CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [74/1998] CRIME_FRAME_NEG (agreement: 80%) | runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [75/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [76/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [77/1998] CRIME_FRAME_NEG (agreement: 80%) | runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [78/1998] NO_CRIME_FRAME (agreement: 60%) | runs: ['CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME']
  [79/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [80/1998] NO_CRIME_FRAME (agreement: 60%) | runs: ['NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG']
  [81/1998] CRIME_FRAME_NEG (agreement: 100%) | runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
  [82/1998] CRIME_FRAME_NEG (agreement: 70%) | runs: ['CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']

### Inspect Hard Cases

Cases with **agreement < 80%** are hard cases — the model is uncertain and your instructions likely need a clearer decision rule for these.

For each hard case, ask:
1. What makes this paragraph ambiguous?
2. Can you write a decision rule that resolves the ambiguity?
3. Is this a genuine borderline case that needs a new label or sub-category?

Then go back to the **Annotation Instructions** cell above, update the instructions, and rerun both 2.1 and 2.2.

In [62]:
run_cols = [f"run_{r+1}" for r in range(N_RUNS)]
explanation_cols = [f"explanation_{r+1}" for r in range(N_RUNS)]

print("=== Full Results (sorted by agreement, lowest first) ===")

annotation_2_2[
    ["agreement", "step2_1_label", "final_label", "text_block_en"] 
    + run_cols 
    + explanation_cols
].sort_values("agreement")

=== Full Results (sorted by agreement, lowest first) ===

,agreement,step2_1_label,final_label,text_block_en,run_1,run_2,run_3,run_4,run_5,run_6,...,explanation_1,explanation_2,explanation_3,explanation_4,explanation_5,explanation_6,explanation_7,explanation_8,explanation_9,explanation_10
0,0.4,CRIME_FRAME_POS,CRIME_FRAME_POS,Bisher wurden in Deutschland 266.975 [Gruppe 1...,CRIME_FRAME_POS,NO_CRIME_FRAME,NO_CRIME_FRAME,CRIME_FRAME_NEG,CRIME_FRAME_POS,NO_CRIME_FRAME,...,**Label: CRIME_FRAME_POS**\n**Explanation:** D...,Der Absatz verknüpft die Gruppe **nicht expliz...,Der Absatz thematisiert zwar **Sicherheitsbede...,Der Absatz verknüpft die **[Gruppe 1]** expliz...,**Label:** **CRIME_FRAME_POS**\n**Explanation:...,Der Absatz spricht zwar **Sicherheitsbedenken*...,Der Absatz thematisiert explizit **Präventions...,Die Gruppe wird zwar im Kontext einer Diskussi...,Der Absatz thematisiert explizit **Präventions...,**Label:** **CRIME_FRAME_NEG**\n**Explanation:...
1,0.4,CRIME_FRAME_NEG,NO_CRIME_FRAME,Laut einer Antwort der Se­natsinnenverwaltung ...,NO_CRIME_FRAME,NO_CRIME_FRAME,CRIME_FRAME_POS,NO_CRIME_FRAME,CRIME_FRAME_POS,CRIME_FRAME_NEG,...,Die Gruppe wird zwar mit Kontrollen und Aufent...,Die Gruppe wird nicht explizit als Quelle von ...,**Label:** CRIME_FRAME_POS\n\n**Explanation:**...,Der Text verknüpft die Gruppe nicht direkt mit...,Der Absatz thematisiert explizit **Präventions...,**Label:** **CRIME_FRAME_NEG**\n**Explanation:...,**Label: CRIME_FRAME_NEG**\n**Explanation:** D...,Die Gruppe wird nicht explizit als Täter oder ...,Der Absatz beschreibt explizit präventive Maßn...,Der Text verbindet die Gruppe explizit mit Kri...
25,0.5,CRIME_FRAME_NEG,CRIME_FRAME_NEG,„Als die Polizei diese mit Spezialkräften durc...,NO_CRIME_FRAME,CRIME_FRAME_NEG,NO_CRIME_FRAME,NO_CRIME_FRAME,CRIME_FRAME_NEG,CRIME_FRAME_POS,...,Der Absatz erwähnt zwar eine Straftat (Messerf...,Der Absatz verknüpft die Gruppe explizit mit e...,Der Absatz führt zwar eine konkrete Straftat (...,Der Absatz verbindet zwar explizit ein Mitglie...,**Label:** **CRIME_FRAME_NEG**\n**Explanation:...,,,Die Gruppe [Gruppe 1] wird explizit als Teil d...,Die Gruppe wird zwar als Wohnbevölkerung einer...,*Der Absatz enthält sowohl eine explizite Verk...
26,0.5,CRIME_FRAME_NEG,NO_CRIME_FRAME,Berlin Der neue ukrainische Botschafter in Ber...,UNCLEAR,NO_CRIME_FRAME,NO_CRIME_FRAME,CRIME_FRAME_NEG,NO_CRIME_FRAME,CRIME_FRAME_NEG,...,**Der Absatz verknüpft [Gruppe 1] zwar mit ein...,**Label: NO_CRIME_FRAME**\n**Explanation:** De...,Der Absatz verknüpft **[Gruppe 1]** explizit n...,Der Absatz verknüpft **[Gruppe 1]** explizit m...,---\n**Label:** **NO_CRIME_FRAME**\n**Explanat...,**Label: CRIME_FRAME_NEG**\n**Explanation:** D...,Der Absatz verknüpft explizit **[Gruppe 1]** m...,Der Absatz verknüpft **[Gruppe 1]** explizit m...,Die im Absatz erwähnte **[Gruppe 1]** wird zwa...,Label: **UNCLEAR**\n\n**Explanation:**\nDer Pa...
27,0.5,CRIME_FRAME_NEG,NO_CRIME_FRAME,\n\nDie Mullahs haben erneut zwei [Gruppe 1] i...,NO_CRIME_FRAME,CRIME_FRAME_NEG,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,...,Die [Gruppe 1] wird nicht als Täterin oder mit...,Die **[Gruppe 1]** wird als Täterin des Vorwur...,**Label: NO_CRIME_FRAME**\n**Explanation:** Di...,Die Gruppe [Gruppe 1] wird nicht als Täterin o...,"Die Gruppe wird hier nicht als Täterin der ""ve...",Die Gruppe wird hier als festgenommene Verdäch...,Die **[Andere Gruppe]** wird direkt als Täteri...,Die [Gruppe 1] wird als Täterin der *versuchte...,Die **[Gruppe 1]** (Frau und Mann) wird expliz...,Die Absätze verknüpfen [Gruppe 1] (Mullahs) di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997,1.0,NO_CRIME_FRAME,NO_CRIME_FRAME,Der Post SV verkaufte sich keinesfalls schlech...,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,...,Der Absatz behandelt ausschliesslich einen spo...,**Label: NO_CRIME_FRAME**\n**Explanation:** De...,**Label:** NO_CRIME_FRAME\n**Explanation:** De...,Der Absatz behandelt ausschließlich einen Spor...,Der Absatz behandelt ausschließlich ein **spor...,Der Text thematisiert ausschließlich sportlich...,DerAbsatz thematisiert ausschließlich einen **...,Der Absatz behandelt ausschließlich sportliche...,Der Absatz behandelt ausschließlich ein Sporte...,Der Text thematisiert weder Kriminalität noch ...
996,1.0,NO_CRIME_FRAME,NO_CRIME_FRAME,"Es sind vor allem Zinssorgen, die den Börsiane...",NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,...,Der Absatz verbindet die Gruppen weder mit Kri...,Der Text verknüpft die Gruppe weder mit Krimin...,**Label: NO_CRIME_FRAME**\n**Explanation:** De...,Der Absatz behandelt ausschließlich wirtschaft...,Der Absatz verknüpft die **[Gruppe 1]** expliz...,Der Absatz verbindet **[Gruppe 1]** (implizit ...,Der Absatz thematisiert wirtschaftliche und en...,Die Gruppe wird lediglich als wirtschaftliche ...,Der Absatz verknüpft die **[Gruppe 1]** und **...,Der Absatz verknüpft die **[Gruppe 1]** und **...
995,1.0,NO_CRIME_FRAME,NO_CRIME_FRAME,Folgt die britische Regierung dem Beispiel der...,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,...,Der Absatz erwähnt zwar die Sanktionsliste der...,**Label:** NO_CRIME_FRAME\n**Explanation:** De...,Der Absatz erwähnt weder explizite Straftaten ...,Der Text erwähnt zwar Sanktionen gegen bestimm...,Der Text erwähnt zwar Sanktionsmaßnahmen gegen...,**Label:** NO_CRIME_FRAME\n**Explanation:** De...,Der Absatz erwähnt zwar Sanktionen und Vorwürf...,Der Absatz verbindet die Gruppe **[Gruppe 1]**...,Der Absatz verknüpft die Gruppe ([Gruppe 1] = ...,"Der Text verknüpft die Gruppe ([Gruppe 1], hie..."
1004,1.0,NO_CRIME_FRAME,NO_CRIME_FRAME,"Mehr als 3,6 Millionen Menschen haben infolge ...",NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,...,"Der Absatz thematisiert ausschließlich Flucht,...",Der Absatz verknüpft die [Gruppe 1] (Ukrainisc...,Der Absatz verknüpft die Gruppe **[Gruppe 1]**...,"Der Absatz thematisiert ausschließlich Flucht,...",Der Absatz thematisiert ausschließlich die Reg...,Der Absatz thematisiert die Unterstützung und ...,Der Absatz thematisiert ausschließlich humanit...,Der Absatz thematisiert ausschließlich humanit...,Der Absatz thematisiert ausschließlich Migrati...,Der Absatz thematisiert ausschließlich die Reg...
1997,1.0,NO_CRIME_FRAME,NO_CRIME_FRAME,PRACHTEXEMPLAR: Einen tollen Fang machte Mathe...,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,NO_CRIME_FRAME,...,"Der Absatz erwähnt weder Kriminalität, Sicherh...",**Label: NO_CRIME_FRAME**\n**Explanation:** De...,Der Absatz erwähnt weder Kriminalität noch Sic...,Der Absatz erwähnt weder Kriminalität noch Sic...,Der Absatz thematisiert ausschließlich die spo...,Der Absatz verknüpft die Gruppe **[Gruppe 1]**...,Der Absatz erwähnt weder Kriminalität noch Sic...,Der Absatz erwähnt die Gruppe **[Gruppe 1]** a...,**Label:** NO_CRIME_FRAME\n**Explanation:** De...,Der Absatz thematisiert ausschließlich sportli...

In [63]:
hard_cases = annotation_2_2[annotation_2_2["agreement"] < 0.8].copy()

print(f"Hard cases (agreement < 80%): {len(hard_cases)} out of {len(annotation_2_2)}")

for _, row in hard_cases.iterrows():
    runs = [row[f"run_{r+1}"] for r in range(N_RUNS)]

    print(f"\n{'='*60}")
    print(f"Agreement: {row['agreement']:.0%}")
    print(f"Step 2.1 label: {row['step2_1_label']}")
    print(f"Final label: {row['final_label']}")
    print(f"Runs: {runs}")
    print(f"Text: {str(row['text_block_en'])[:500]}...")
    print("→ TODO: Why is this hard? What decision rule would resolve it?")

Hard cases (agreement < 80%): 266 out of 1998

============================================================
Agreement: 40%
Step 2.1 label: CRIME_FRAME_POS
Final label: CRIME_FRAME_POS
Runs: ['CRIME_FRAME_POS', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_POS', 'NO_CRIME_FRAME', 'CRIME_FRAME_POS', 'NO_CRIME_FRAME', 'CRIME_FRAME_POS', 'CRIME_FRAME_NEG']
Text: Bisher wurden in Deutschland 266.975 [Gruppe 1] aus der Ukraine erfasst, gab das Bundesinnenministerium am Sonntag bekannt. [Andere Gruppe] müssen sich nicht bei den deutschen Behörden registrieren, weil sie für 90 Tage visumfrei einreisen können. Erfasst werden sie bei den Behörden erst, wenn sie sich dort melden, etwa um staatliche Hilfe in Anspruch zu nehmen.

Unter anderem der bayerische Innenminister Joachim Herrmann (CSU) hatte zuvor vor einer Sicherheitslücke bei der Aufnahme ukrainischer...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 40%
Step 2.1 label: CRIME_FRAME_NEG
Final label: NO_CRIME_FRAME
Runs: ['NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_POS', 'NO_CRIME_FRAME', 'CRIME_FRAME_POS', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_POS', 'CRIME_FRAME_NEG']
Text: Laut einer Antwort der Se­natsinnenverwaltung auf eine Anfrage der Linken-Abgeordneten Elif Eralp und Niklas Schrader werden dabei neben geringfügigen Drogendelikten wie dem Besitz von Cannabis vor allem Verstöße gegen das Aufenthaltsgesetz verzeichnet, 388 Fälle waren es im ersten Halbjahr 2022. Kontrolliert werden also überwiegend nichtweiße Personen, kritisieren die Abgeordneten.

„Die polizeilichen Maßnahmen bringen außer kurzfristigen Verdrängungseffekten nichts“, kritisiert auch die Initia...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: CRIME_FRAME_NEG
Runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG']
Text: Der Mann am späten Sonntagnachmittag in seiner Wohnung im Obergeschoss eines Plattenbaus am Unterhorstweg randaliert. Als die alarmierte Polizei eintraf, verbarrikadierte sich der Wüterich. Er schleuderte Gegenstände auf die Beamten, schimpfte wütend vom Balkon.

Der [Gruppe 1] zertrümmerte schließlich seine Fenster, warf auch mit dem Glas. Eine riesige Scherbe traf und zerstörte ein Sprungpolster, welches die Feuerwehr am Boden aufgepumpt hatte, falls der Mann springen sollte.

Während die Kame...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: NO_CRIME_FRAME
Runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_POS', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG']
Text: WELT: Was passt Ihnen denn nicht?

Metsola: Es ist beispielsweise nicht akzeptabel, dass sich die EU-Staaten seit Jahren nicht auf eine einheitliche Asylpolitik und eine solidarische Verteilung von [Gruppe 1] einigen können. Ich weiß, das ist ein schwieriges Thema. Aber die Menschen erwarten hier endlich eine Lösung. Wir sind Mit-Gesetzgeber und werden uns nicht abspeisen lassen mit immer neuen Absichtserklärungen bei EU-Gipfeln oder bei den Treffen der Innenminister. Wir erwarten, dass die EU-K...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: NO_CRIME_FRAME
Runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME']
Text: 1917 stellten sie ihre khasarische Armee, die Bolschewiki, zusammen und infiltrierten und übernahmen Russland. Sie haben den Zaren und seine Familie kaltblütig ermordet und alle russischen Gold-, Silber- und Kunstschätze gestohlen. Kurz vor dem Zweiten Weltkrieg ermordeten sie die österreichische und deutsche Königsfamilie.

Clif High sagt, was derzeit in der Ukraine passiert, wird im Westen nicht genau dargestellt. Er sieht die russische Invasion als Kampf gegen die Khasaren-Mafia und ihre Pand...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: CRIME_FRAME_NEG
Runs: ['CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
Text: Berlin - Nach dem gewaltsamen Tod einer zweifachen Mutter aus Afghanistan beginnt am heutigen Mittwoch (10.00 Uhr) vor dem Berliner Landgericht der Prozess gegen deren Brüder. Die Staatsanwaltschaft geht davon aus, dass die Männer die 34-Jährige getötet haben, weil sie sich nicht den Moralvorstellungen der Familie unterworfen habe. Die Anklage wirft ihnen einen Mord aus niederen Beweggründen vor. Die 27 und 23 Jahre alten Männer sollen ihre Schwester am 13. Juli 2021 getötet, dann deren Leiche i...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: CRIME_FRAME_NEG
Runs: ['CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME']
Text: Biden forderte die Menschen außerdem auf, Corona nicht als parteipolitischen Streitpunkt zu betrachten. „Lasst uns aufhören, uns gegenseitig als Feinde zu sehen, und anfangen, uns als das zu sehen, was wir sind, nämlich Mitbürger.“ Es gehe darum, Probleme gemeinsam anzugehen, um vorwärts zu kommen. Seit Beginn der Pandemie sind in den USA mehr als 950.000 Menschen im Zusammenhang mit einer Corona-Infektion gestorben. Die Impfquote stagniert.

Während Demokraten Bidens Rede bejubelten, beklagten ...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: NO_CRIME_FRAME
Runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME']
Text: Öffentliches Leben weiter eingeschränkt

Mit weiteren Anordnungen schränkten die [Gruppe 1] in dieser Woche das öffentliche Leben in dem Land noch mehr ein: So dürfen [Andere Gruppe] künftig ohne einen männlichen Begleiter nicht mehr fliegen. Die Taliban wiesen Fluglinien im Land an, an Frauen ohne Begleiter keine Tickets mehr zu verkaufen, wie aus einem Dokument hervorging, das der Deutschen Presse-Agentur vorlag. Zudem dürfen in der Hauptstadt Kabul und Umgebung Freizeitparks nur noch nach Ges...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: NO_CRIME_FRAME
Runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
Text: Platz 3: Eine deutsche IS-Anhängerin aus Osnabrück nahm ihre sechsjährige Tochter in Syrien zur Steinigung mit.

Platz 2: Moslemische [Andere Gruppe] aus Tunesien und Nigeria vergewaltigen 18-jährige [Gruppe 1], die anschließend ins sicherere [Andere Gruppe] weiterflüchtet.

Platz 1: [Andere Gruppe] kämpfen auf beiden Seiten im Ukraine-Krieg (mit Videos):...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: NO_CRIME_FRAME
Runs: ['NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME']
Text: Regierungsmitglieder äußerten sich zurückhaltend kritisch zu Ben Gvirs Aktion. Seine Präsenz in der Gegend werde nicht dazu beitragen, die Gemüter zu besänftigen, sagte der Generaldirektor des Ministeriums für öffentliche Sicherheit, Tomer Lotan, im Radio. Schärfer fiel der Kommentar eines Abgeordneten der linken Partei Meretz aus, Mossi Raz: Wer ankündige, in dem palästinensischen Stadtteil Scheich Jarrah ein Büro zu eröffnen, „versucht, Feuer zu legen und einen Krieg auszulösen, wie im vergang...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: NO_CRIME_FRAME
Runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME']
Text: Überall in Deutschland, auch in Berlin, gründen sich Anfang der 80er Jahre Jugendgangs, meist in den „klassischen Arbeitervierteln“. So schreiben es die Autoren Klaus Farin und Eberhard Seidel in ihrem Buch „Krieg in den Städten: Jugendgangs in Deutschland“. Darin heißt es auch: „Die meisten von ihnen werden von jugendlichen [Andere Gruppe] dominiert.“ Vor dem Mauerfall gehören nach Schätzungen der Polizei allein in West-Berlin mehr als 4000 Jugendliche zwischen 14 und 25 Jahren zu solchen Grupp...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_POS
Final label: CRIME_FRAME_POS
Runs: ['CRIME_FRAME_POS', 'CRIME_FRAME_POS', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_POS', 'CRIME_FRAME_POS', 'NO_CRIME_FRAME', 'CRIME_FRAME_POS', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME']
Text: Ehrenamtliche Helfer:innen kritisieren, dass keine Vermittlung stattfindet und deren Expertise nicht berücksichtigt werde. Die Sozialverwaltung weist dies zurück und sagt, Repräsentanten der Ehrenamtlichen seien in regelmäßige, wöchentliche Gespräche einbezogen.

Karuna-Vorstand Jörg Richert erklärte dem Tagesspiegel, man habe am Hauptbahnhof wegen des großen Ansturms keine Vermittlung zwischen Privatleuten und [Gruppe 1] mehr durchführen können. Künftig werde es ein nachprüfbares Verfahren gebe...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: NO_CRIME_FRAME
Runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME']
Text: Grund zur Beruhigung ist das nicht. Nach Einschätzungen von Expertinnen und Experten ist die Bedrohungslage für ankommende [Gruppe 1] sehr real. Die Sozialarbeiterin und Frauenrechtlerin Sabine Constabel macht in einem Interview mit den Stuttgarter Nachrichten auf die besondere Form der Ansprache von [Andere Gruppe] Frauen aufmerksam: „Die Befürchtung ist, dass da auch Menschenhändler, so genannte Loverboys, unterwegs sind, die erst mal sehr nett zu den Frauen sind, sich um sie kümmern, vielleic...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: CRIME_FRAME_NEG
Runs: ['CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME']
Text: Ein besonderer, ein emotionaler Gang. Der wenige Tage nach der Schändung der Gedenkbäume für die Opfer von Buchenwald eine zusätzliche Aufladung erfährt. Denn dieser Marsch ist auch eine Antwort.

So sehen das auch die Gäste, die später in ihren kurzen Ansprachen erinnern, was dieser Ort war. Naftali Fürst, Präsident des Internationalen Komitees Buchenwald-Dora, der als Kind die Hölle von Buchenwald überlebte, beschwor in einer übermittelten Botschaft die Pflicht, die Stimme gegen das Vergessen ...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: NO_CRIME_FRAME
Runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME']
Text: Falsche Identität als syrischer [Gruppe 1] zugelegt

Der derzeit vom Dienst freigestellte Bundeswehrsoldat aus Offenbach hatte sich eine falsche Identität als syrischer [Gruppe 1] zugelegt und in diesem Zusammenhang Sach- und Dienstleistungen bezogen. Franco A. war im Februar 2017 auf dem Wiener Flughafen festgenommen worden, als er eine geladene Pistole aus einem Versteck in einer Flughafentoilette holen wollte. Woher die Waffe stammt und was er damit plante, blieb zunächst unklar.

Zugunsten d...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: CRIME_FRAME_NEG
Runs: ['CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME']
Text: Noch am 23. Mai hatte Peskow ausdrücklich bezweifelt, dass Medwedtschuk als ukrainischer Staatsbürger und Zivilist gegen ukrainische Soldaten oder gar die Verteidiger des „Asowstal“-Stahlwerks ausgetauscht werden könne. Russlands Propaganda lastete alle Zerstörungen in der nach zähen Kämpfen eroberten Hafenstadt „neonazistischen“ Verteidigern an, gegen die in Moskau unter anderem ein Tribunal nach dem Muster der Nürnberger Prozesse gefordert wurde. Peskow sagte seinerzeit, „Soldaten und Gefangen...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: NO_CRIME_FRAME
Runs: ['NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME']
Text: Ebenfalls am 5. Februar um 20.15 Uhr macht sich Nils Straatmann "2000 Jahre später - Zu Fuß durch Israel und Palästina" auf. Es ist die Geburtsstätte dreier Weltreligionen und doch vor allem für den Konflikt bekannt, der den Nahen Osten seit Jahrhunderten begleitet. Straatmann begibt sich auf eine aufrüttelnde Wanderung und trifft auf Mauern, Panzer und Soldaten, aber auch auf Hoffnung, Gastfreundschaft und Weisheit. Farbig und orientalisch wird es dann einen Tag später mit großartigen Naturschö...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: NO_CRIME_FRAME
Runs: ['NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
Text: Für die tödliche Messerattacke auf arglose Passanten schickt das Landgericht Würzburg einen psychisch kranken Mann unbefristet in eine Psychiatrie. Das sagte der Vorsitzende Richter, Thomas Schuster, am Dienstag bei der Urteilsverkündung.

Es ist erwiesen, dass der zur Tatzeit schuldunfähige Beschuldigte am 25. Juni 2021 in der Würzburger Innenstadt wahllos Menschen mit einem Küchenmesser angriff. Drei Frauen starben, neun Menschen wurden verletzt. Der aus Somalia [Gruppe 1] ist laut zweier unab...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: NO_CRIME_FRAME
Runs: ['NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG']
Text: Im August attackierten türkische Streitkräfte Stellungen der PKK im türkischen Gaziantep.

Nach dem Bombenanschlag in Istanbul ist sich die türkische Regierung schnell sicher, dass [Gruppe 1] aus Nordsyrien den Auftrag gaben. Nun erfolgt die Antwort Ankaras. Die Luftwaffe fliegt Angriffe vor allem auf die Stadt Kobane und soll dabei nach Angaben einer NGO zwölf Menschen getötet haben.

Die Türkei hat nach Angaben syrisch-kurdischer Kämpfer am Samstag mehrere Orte im Norden Syriens bombardiert, d...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: NO_CRIME_FRAME
Runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG']
Text: Seit mehr als sieben Monaten erreicht uns Tag für Tag eine Kriegsberichterstattung aus der Ukraine, die sich die russischen Aggressoren zunächst in einem „Blitzkrieg“, später in einem Ermüdungskrieg aneignen wollten. Egal, wie deprimierend oder hoffnungsvoll die Kriegsberichte stimmen können, eines haben sie alle gemein: Sie sind Zeugnisse des blanken Horrors.

Und es ist die schreckliche Bestätigung dessen, dass auch nach den Jahrzehnten der Vergangenheitsbewältigung in Europa Menschen auf dies...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: NO_CRIME_FRAME
Runs: ['NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG']
Text: Dies könnte im ersten Wahlgang zu einer Ausnahmesituation in Westeuropa führen, bei der der identitäre Kandidat Zemmour, der den Bezug auf Charles de Gaulle missbraucht, vor der Kandidatin der konservativen „Les Républicains“, Valérie Pécresse, landet. Vor allem die radikale Rechte breitet sich zunehmend aus. „Les Républicains“, die in einen liberal-konservativen und einen souveränistisch-identitären Flügel gespalten sind, standen indessen in den Umfragen noch nie so niedrig da.

Die Gründe für ...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: NO_CRIME_FRAME
Runs: ['NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'CRIME_FRAME_NEG', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'NO_CRIME_FRAME', 'CRIME_FRAME_NEG']
Text: Der SPD-Vorsitzende Lars Klingbeil hält die Einheit von Ost und West in Deutschland für weiter fortgeschritten als noch vor zehn Jahren. "Was die Ost-West-Frage betrifft, sind wir vorangekommen", sagte er der "Rheinischen Post" (Montagsausgabe). "Wir haben eine stärkere Deutsche Einheit als es etwa vor zehn Jahren noch der Fall war."

Der Osten sei attraktiv, was die Industrieansiedlungen von Intel und Tesla zeigten, und auch zu Recht deutlich selbstbewusster. "Aber unser Land befindet sich gera...
→ TODO: Why is this hard? What decision rule would resolve it?

============================================================
Agreement: 50%
Step 2.1 label: CRIME_FRAME_NEG
Final label: CRIME_FRAME_NEG

In [64]:
#check hardcases in detail! 

row = hard_cases.iloc[0] #checks first one needs to be changed if multiple

print("ARTICLE ID:", row["article_id"])
print("PAR INDEX:", row["par_index"])
print("GROUP:", row["group"])
print("AGREEMENT:", row["agreement"])
print("STEP 2.1 LABEL:", row["step2_1_label"])
print("FINAL LABEL:", row["final_label"])

print("\nTEXT:\n")
print(row["text_block_en"])

print("\nRUNS AND EXPLANATIONS:\n")
for r in range(N_RUNS):
    print(f"\n--- Run {r+1} ---")
    print("Label:", row[f"run_{r+1}"])
    print("Explanation:", row[f"explanation_{r+1}"])

ARTICLE ID: Tonline_added_1e21630211a305730c36fd6115990fa76b1cebe0_
PAR INDEX: 9
GROUP: REFUG
AGREEMENT: 0.4
STEP 2.1 LABEL: CRIME_FRAME_POS
FINAL LABEL: CRIME_FRAME_POS

TEXT:

Bisher wurden in Deutschland 266.975 [Gruppe 1] aus der Ukraine erfasst, gab das Bundesinnenministerium am Sonntag bekannt. [Andere Gruppe] müssen sich nicht bei den deutschen Behörden registrieren, weil sie für 90 Tage visumfrei einreisen können. Erfasst werden sie bei den Behörden erst, wenn sie sich dort melden, etwa um staatliche Hilfe in Anspruch zu nehmen.

Unter anderem der bayerische Innenminister Joachim Herrmann (CSU) hatte zuvor vor einer Sicherheitslücke bei der Aufnahme ukrainischer [Gruppe 1] gewarnt. "Es ist wichtig, dass durch erkennungsdienstliche Maßnahmen die Identifizierbarkeit der ankommenden Personen sichergestellt wird", sagte der Vorsitzende der Innenministerkonferenz den Zeitungen der Funke Mediengruppe.

Herrmann rief die anderen Bundesländer dazu auf, dem bayerischen Beispiel zu folgen. Dort registriere die Polizei ankommende Kriegsflüchtlinge nicht nur, sondern es gebe auch erkennungsdienstliche Maßnahmen. Die Personalien würden mit den Fahndungsdatenbanken abgeglichen. "Ich erwarte auch von den anderen Bundesländern hier ein strukturiertes und koordiniertes Vorgehen", sagte der CSU-Politiker.

RUNS AND EXPLANATIONS:


--- Run 1 ---
Label: CRIME_FRAME_POS
Explanation: **Label: CRIME_FRAME_POS**
**Explanation:** Der Absatz thematisiert explizit Sicherheitsmaßnahmen (registrierungsdienstliche und erkennungsdienstliche Verfahrensweisen, Abgleich mit Fahndungsdatenbanken) im Kontext der **[Gruppe 1]**, die als präventive **Sicherheits- und Kontrollmaßnahme** dargestellt werden, ohne eine kriminelle Zuschreibung. Die Gruppe wird nicht als Täter oder Gefahr, sondern als Gegenstand von Präventionsbemühungen präsentiert.

--- Run 2 ---
Label: NO_CRIME_FRAME
Explanation: Der Absatz verknüpft die Gruppe **nicht explizit mit Kriminalität oder Sicherheitsrisiken**, sondern thematisiert **Sicherheitsmaßnahmen und Registrierung als präventive Verwaltungspraxis** – ohne direkte Zuschreibung von Straftaten oder Bedrohungen. Die Warnung vor einer "Sicherheitslücke" bezieht sich auf Identifizierbarkeit zur **Vermeidung potenzieller Risiken**, nicht auf tatsächliche Kriminalität der Gruppe selbst.

--- Run 3 ---
Label: NO_CRIME_FRAME
Explanation: Der Absatz thematisiert zwar **Sicherheitsbedenken** (z. B. *„Sicherheitslücke“*, *„erkennungsdienstliche Maßnahmen“*), bezieht diese jedoch explizit auf die **Vermeidung einer potenziellen Registrierungslücke** – nicht auf eine konkrete Kriminalitäts- oder Gewaltverknüpfung der [Gruppe 1] mit Straftaten oder Sicherheitsrisiken, sondern auf **administrative Präventionsmaßnahmen** zur Identifizierung von Geflüchteten. Eine direkte Assoziierung der Gruppe mit Kriminalität oder Terrorismus fehlt.

--- Run 4 ---
Label: CRIME_FRAME_NEG
Explanation: Der Absatz verknüpft die **[Gruppe 1]** explizit mit einer **Sicherheitslücke** und einer **Gefahr für die öffentliche Sicherheit**, indem die Notwendigkeit von erkennungsdienstlichen Maßnahmen zur Identifizierbarkeit und Fahndungsabgleichen hervorgehoben wird (Bedrohungsrahmen).

--- Run 5 ---
Label: CRIME_FRAME_POS
Explanation: **Label:** **CRIME_FRAME_POS**
**Explanation:** Der Absatz thematisiert explizit **Sicherheitsmaßnahmen** (Erkennungsdienstliche Maßnahmen, Datenabgleich mit Fahndungsdatenbanken) im Zusammenhang mit der Gruppe ([Gruppe 1] aus der Ukraine), die auf **Prävention und Risikominimierung** abzielen, ohne die Gruppe selbst als kriminell oder gefährlich zu darstellen.

--- Run 6 ---
Label: NO_CRIME_FRAME
Explanation: Der Absatz spricht zwar **Sicherheitsbedenken** im Zusammenhang mit der Registrierung der Gruppe an, verknüpft diese jedoch nicht explizit mit **Kriminalität, Terrorismus, Gewalt oder Straftaten** – es geht einzig um die **Identifizierbarkeit von Kriegsflüchtlingen** (Prävention potenzieller Sicherheitslücken). Da keine direkte Täterschaft, Gefahr oder Legitimierung von Gewalt durch die Gruppe benannt wird, zählt dies nicht als **CRIME_FRAME_NEG** oder **POS**.

--- Run 7 ---
Label: CRIME_FRAME_POS
Explanation: Der Absatz thematisiert explizit **Präventionsmaßnahmen** (erkenntnnisdienstliche Maßnahmen, Registrierung, Datenabgleich) zur **Sicherheit im Zusammenhang mit [Gruppe 1]**, ohne dabei eine kriminelle oder gefährdende Darstellung vorzunehmen.

--- Run 8 ---
Label: NO_CRIME_FRAME
Explanation: Die Gruppe wird zwar im Kontext einer Diskussion über Sicherheitsmaßnahmen erwähnt, aber es liegt **keine Verknüpfung mit konkreter Kriminalität, Terrorismus oder Gewalt** vor – stattdessen geht es um generelle Identitätsfeststellung und behördliche Registrierung, was allein keinen Kriminalitätsrahmen darstellt.

--- Run 9 ---
Label: CRIME_FRAME_POS
Explanation: Der Absatz thematisiert explizit **Präventionsmaßnahmen** (erkennungsdienstliche Maßnahmen, Personalienabgleich mit Fahndungsdatenbanken) zur **Sicherheit** der Gruppe ([Gruppe 1]) und ihrer Integration, ohne diese als Bedrohung darzustellen.

--- Run 10 ---
Label: CRIME_FRAME_NEG
Explanation: **Label:** **CRIME_FRAME_NEG**
**Explanation:** Der Absatz verknüpft explizit die **[Gruppe 1]** (ukrainische Geflüchtete) mit einer **Sicherheitslücke** und der **Forderung nach erkennungsdienstlichen Maßnahmen** zur Identifizierbarkeit, was sie als **potenzielle Gefahr** oder **Kriminalitätsrisiko** impliziert.

In [65]:
# Agreement summary
print("=== Agreement Distribution ===")
print(annotation_2_2["agreement"].describe().round(2))

print(f"\nFull agreement (1.00): {len(annotation_2_2[annotation_2_2['agreement'] == 1.0])} rows")
print(f"Hard cases (<0.80):    {len(annotation_2_2[annotation_2_2['agreement'] < 0.8])} rows")
print(f"Very hard (<0.60):     {len(annotation_2_2[annotation_2_2['agreement'] < 0.6])} rows")

print("\n=== Final Label Distribution ===")
print(annotation_2_2["final_label"].value_counts())

=== Agreement Distribution ===
count    1998.00
mean        0.93
std         0.13
min         0.40
25%         0.90
50%         1.00
75%         1.00
max         1.00
Name: agreement, dtype: float64

Full agreement (1.00): 1493 rows
Hard cases (<0.80):    266 rows
Very hard (<0.60):     44 rows

=== Final Label Distribution ===
final_label
NO_CRIME_FRAME     1220
CRIME_FRAME_NEG     763
CRIME_FRAME_POS      15
Name: count, dtype: int64

In [66]:
# Save hard cases continuously, but replace old duplicates with the newest version
hard_cases["source_step"] = "2.2_multiple_runs"
hard_cases["n_runs"] = N_RUNS
hard_cases["temperature"] = TEMPERATURE
hard_cases["fill_seed"] = NO_CRIME_FILL_SEED

if HARD_CASES_FRAME.exists():
    old_hard_cases = pd.read_csv(HARD_CASES_FRAME)

    combined_hard_cases = pd.concat(
        [old_hard_cases, hard_cases],
        ignore_index=True
    )

    # keep the newest version when article_id + par_index already exists
    combined_hard_cases = combined_hard_cases.drop_duplicates(
        subset=["article_id", "par_index"],
        keep="last"
    )
else:
    combined_hard_cases = hard_cases.copy()

combined_hard_cases.to_csv(HARD_CASES_FRAME, index=False)

print(f"Saved hard cases to {HARD_CASES_FRAME}")
print(f"Total hard cases saved: {len(combined_hard_cases)}")

Saved hard cases to results/hard_cases.csv
Total hard cases saved: 323

## Next Steps

After inspecting the results:

1. **Note problems** — write down what went wrong and why in a markdown cell or comment
2. **Update instructions** — go back to the instructions cell and add/clarify decision rules
3. **Repeat 2.1 and 2.2** — rerun both steps with the updated instructions
4. **Stop when** your instructions broadly cover the cases you see, even if reliability is not yet perfect

Once coverage is broad, move to **Step 3** — testing on a curated sample of hard and soft cases with human gold-standard labels, adding chain-of-thought prompting and few-shot examples.

---

### Notes on This Round (fill in as you iterate)

| Round | Problem Identified | Decision Rule Added |
|-------|-------------------|---------------------|
| 1  (Seed 42, n= 200)   |Model is unsure whether CRIME_FRAME_NEG requires the group to be the actual perpetrator, or whether it is enough that the group praises, legitimizes, supports, or is linked to a terror attack. -> Should label as CRIME_FRAME_NEG| Zusätzliche Entscheidungsregel zu Terrorismus, Anschlägen und Gewaltlegitimation: Wenn eine Gruppe einen Anschlag, Terrorakt, Gewaltakt oder eine Straftat ausdrücklich begrüßt, legitimiert, feiert, rechtfertigt oder als Widerstand bzw. heroische Operation darstellt, vergeben Sie CRIME_FRAME_NEG, auch wenn die Gruppe keine direkte Verantwortung übernimmt oder nicht eindeutig als Täter genannt wird. Dies gilt auch dann, wenn die Gruppe eher als Unterstützer, Kommentator, ideologischer Bezugspunkt oder politischer Akteur erscheint, solange sie explizit mit Zustimmung, Rechtfertigung, Feier, Unterstützung oder ideologischer Nähe zu Terrorismus, politischer Gewalt oder Straftaten verbunden wird. Krieg, geopolitische Konflikte oder militärische Ereignisse sind nur dann CRIME_FRAME_NEG, wenn die Gruppe explizit mit Terrorismus, Anschlägen, Gewalt gegen Zivilisten, Straftaten oder Sicherheitsbedrohungen verbunden wird. |
| 2     |                   |                     |
| 3     |                   |                     |